# TCInvest Raw Review Manual Inspection

This notebook is for **read-only human QA** of the current primary raw review datasets before downstream analysis. It supports inspection, searching, filtering, sorting, and sampling only. It does not modify raw or processed data, clean text, classify reviews, run sentiment/topic models, or select complaints.

In [21]:
from pathlib import Path

import pandas as pd
from IPython.display import display

pd.set_option("display.max_colwidth", 300)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

def find_project_root():
    for candidate in [Path.cwd(), *Path.cwd().parents]:
        if (candidate / "01_data").is_dir() and (candidate / "03_notebooks").is_dir():
            return candidate
    raise FileNotFoundError("Could not locate the project root from the current working directory.")

PROJECT_ROOT = find_project_root()
APP_STORE_PATH = PROJECT_ROOT / "01_data/raw/app_store/2026-09-22_app_store_raw_expanded_v2.csv"
GOOGLE_PLAY_PATH = PROJECT_ROOT / "01_data/raw/google_play/2026-09-22_google_play_raw.csv"
CLEAN_PATH = PROJECT_ROOT / "01_data/processed/reviews_clean_full.csv"
REJECTED_PATH = PROJECT_ROOT / "01_data/processed/reviews_rejected.csv"

app_store_df = pd.read_csv(APP_STORE_PATH, dtype={"review_id": "string"})
google_play_df = pd.read_csv(GOOGLE_PLAY_PATH, dtype={"reviewId": "string"})

print(f"Project root: {PROJECT_ROOT}")
print(f"App Store input: {APP_STORE_PATH.relative_to(PROJECT_ROOT)}")
print(f"Google Play input: {GOOGLE_PLAY_PATH.relative_to(PROJECT_ROOT)}")

Project root: /Users/ndmaivy/Documents/Mai Vy/FBAS6/nhom-nam-nguoi
App Store input: 01_data/raw/app_store/2026-09-22_app_store_raw_expanded_v2.csv
Google Play input: 01_data/raw/google_play/2026-09-22_google_play_raw.csv

## Dataset Overview

In [22]:
app_dates = pd.to_datetime(app_store_df["updated_at"], utc=True, errors="coerce")
google_dates = pd.to_datetime(google_play_df["at"], utc=True, errors="coerce")

assert len(app_store_df) == 522
assert app_store_df["review_id"].nunique() == 522
assert app_dates.min() == pd.Timestamp("2023-04-14T03:22:33+00:00")
assert app_dates.max() == pd.Timestamp("2026-09-14T07:44:28+00:00")
assert len(google_play_df) == 3223
assert google_play_df["reviewId"].nunique() == 3223
assert google_dates.min() == pd.Timestamp("2015-08-13T11:10:30+00:00")
assert google_dates.max() == pd.Timestamp("2026-09-21T12:13:27+00:00")

overview = pd.DataFrame([
    {"source": "App Store", "rows": len(app_store_df), "unique_review_ids": app_store_df["review_id"].nunique(), "earliest": app_dates.min(), "latest": app_dates.max()},
    {"source": "Google Play", "rows": len(google_play_df), "unique_review_ids": google_play_df["reviewId"].nunique(), "earliest": google_dates.min(), "latest": google_dates.max()},
])
display(overview)
print(f"Total current primary raw records: {len(app_store_df) + len(google_play_df):,}")

for label, frame in [("APP STORE", app_store_df), ("GOOGLE PLAY", google_play_df)]:
    print(f"\n{label}: shape={frame.shape}")
    print("Columns:", frame.columns.tolist())
    display(frame.dtypes.rename("dtype").to_frame())
    display(frame.head(3))

,source,rows,unique_review_ids,earliest,latest
0,App Store,522,522,2023-04-14 03:22:33+00:00,2026-09-14 07:44:28+00:00
1,Google Play,3223,3223,2015-08-13 11:10:30+00:00,2026-09-21 12:13:27+00:00

Total current primary raw records: 3,745

APP STORE: shape=(522, 19)
Columns: ['review_id', 'user_name', 'rating', 'title', 'content', 'app_version', 'updated_at', 'vote_sum', 'vote_count', 'source', 'endpoint', 'lang', 'storefront', 'raw_occurrence_count', 'raw_source_files', 'source_groups', 'endpoint_groups', 'belongs_to_tcinvest_response', 'substantive_conflict_fields']

                                dtype
review_id                      string
user_name                         str
rating                          int64
title                             str
content                           str
app_version                       str
updated_at                        str
vote_sum                        int64
vote_count                      int64
source                            str
endpoint                          str
lang                              str
storefront                        str
raw_occurrence_count            int64
raw_source_files                  str
source_groups                     str
endpoint_groups                   str
belongs_to_tcinvest_response     bool
substantive_conflict_fields   float64

,review_id,user_name,rating,title,content,app_version,updated_at,vote_sum,vote_count,source,endpoint,lang,storefront,raw_occurrence_count,raw_source_files,source_groups,endpoint_groups,belongs_to_tcinvest_response,substantive_conflict_fields
0,14548034358,Lethuylinh1004,1,Liên tục lỗi không thể truy cập,"Là một người dùng lâu năm của tech, ban đầu rất hài lòng về chất lượng và giao diện của app, dễ giao dịch. Nhưng vài tháng trở lại đây app lỗi rất nhiều, chỉ đăng nhập có lúc đợi cả 5p vẫn chưa đăng nhập vào trang chủ được, thứ 2 là quảng cáo nhiều, truy cập vào được tài khoản thì phải tắt 7749 ...",6.4.6,2026-09-14T00:44:28-07:00,0,0,App Store,vn|json|default|page=1,unknown,vn,5,diagnostics/recency_2026-09-22/vn_page_01_default.json;diagnostics/recency_2026-09-22/vn_page_01_mostHelpful.xml;diagnostics/recency_2026-09-22/vn_top_mostHelpful.json;diagnostics/recency_2026-09-22/vn_top_mostHelpful.xml;diagnostics/recency_2026-09-22/vn_top_mostrecent.json,diagnostic_recency_2026-09-22,vn|json|default|page=1;vn|json|mostHelpful|page=top;vn|json|mostrecent|page=top;vn|xml|mostHelpful|page=1;vn|xml|mostHelpful|page=top,True,NaN
1,14520064997,Abcdef847362,1,Tần suất bị lỗi mục tài sản quá nhiều,Rất hay bị lỗi báo k có tiền k có cổ phiếu nào trong tài khoản,6.4.6,2026-09-06T21:11:54-07:00,0,0,App Store,vn|json|default|page=1,unknown,vn,5,diagnostics/recency_2026-09-22/vn_page_01_default.json;diagnostics/recency_2026-09-22/vn_page_01_mostHelpful.xml;diagnostics/recency_2026-09-22/vn_top_mostHelpful.json;diagnostics/recency_2026-09-22/vn_top_mostHelpful.xml;diagnostics/recency_2026-09-22/vn_top_mostrecent.json,diagnostic_recency_2026-09-22,vn|json|default|page=1;vn|json|mostHelpful|page=top;vn|json|mostrecent|page=top;vn|xml|mostHelpful|page=1;vn|xml|mostHelpful|page=top,True,NaN
2,14520054584,Vy11229,2,Khá tệ,"App rất lag, đôi khi còn không vào được",6.4.6,2026-09-06T21:07:12-07:00,0,0,App Store,vn|json|default|page=1,unknown,vn,5,diagnostics/recency_2026-09-22/vn_page_01_default.json;diagnostics/recency_2026-09-22/vn_page_01_mostHelpful.xml;diagnostics/recency_2026-09-22/vn_top_mostHelpful.json;diagnostics/recency_2026-09-22/vn_top_mostHelpful.xml;diagnostics/recency_2026-09-22/vn_top_mostrecent.json,diagnostic_recency_2026-09-22,vn|json|default|page=1;vn|json|mostHelpful|page=top;vn|json|mostrecent|page=top;vn|xml|mostHelpful|page=1;vn|xml|mostHelpful|page=top,True,NaN

GOOGLE PLAY: shape=(3223, 16)
Columns: ['reviewId', 'userName', 'userImage', 'content', 'score', 'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent', 'repliedAt', 'appVersion', 'source', 'collection_language', 'collection_country', 'collection_locale', 'retrieved_from_locales']

                         dtype
reviewId                string
userName                   str
userImage                  str
content                    str
score                    int64
thumbsUpCount            int64
reviewCreatedVersion       str
at                         str
replyContent               str
repliedAt                  str
appVersion                 str
source                     str
collection_language        str
collection_country         str
collection_locale          str
retrieved_from_locales     str

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,source,collection_language,collection_country,collection_locale,retrieved_from_locales
0,6638c299-2864-4386-837e-41064b75be48,Thanh Son Huynh,https://play-lh.googleusercontent.com/a-/ALV-UjWVYyexHJs75plCofmmf_iI7Pk1lf4Io7Z1kkaN4-AfMoEUGsE,sao cứ cứng đơ không nhích nhút gõ bất kỳ một chữ nào được....,1,0,NaN,2026-09-21 12:13:27,NaN,NaN,NaN,Google Play,vi,vn,vi_vn,vi_vn
1,45b7bb0f-cd74-43a9-9b85-bd050b6a1f9f,Trần Sáng,https://play-lh.googleusercontent.com/a-/ALV-UjWDFhUdypUfx0qgj3S14QrZKIX8zk_nR6cCNL_RERIgIa6itHms,Mới dùng thử . App giao diên quá chán. Dùng tcbs . Mà phải vào ssi xem giá . .ap quá chán luôn .,1,0,6.4.5,2026-09-21 05:51:18,NaN,NaN,6.4.5,Google Play,vi,vn,vi_vn,vi_vn
2,4ae66065-e785-4516-a20d-51040c7a80d2,Đạt Triệu Phú,https://play-lh.googleusercontent.com/a-/ALV-UjUAi2T5ImLrtRxmPZRNM-XbtRV83EVDxssew8Cwt3ZXKg1u6dE,"rẻ rách, đã rườm rà còn khó xài",1,0,6.4.5,2026-09-18 18:49:22,NaN,NaN,6.4.5,Google Play,vi,vn,vi_vn,vi_vn

## Readable Preview Tables

The App Store `lang` field is shown only as saved metadata; it may be unknown or heuristic and is not treated as language ground truth. Google Play `collection_locale` is collection metadata, not detected review language.

In [23]:
app_preview_columns = ["review_id", "rating", "title", "content", "updated_at", "app_version", "storefront"]
if "lang" in app_store_df.columns:
    app_preview_columns.append("lang")
app_store_preview = app_store_df[app_preview_columns].copy()

google_preview_columns = ["reviewId", "score", "content", "at", "reviewCreatedVersion", "appVersion", "collection_locale"]
google_play_preview = google_play_df[google_preview_columns].copy()

print("App Store readable preview")
display(app_store_preview.head(10))
print("Google Play readable preview")
display(google_play_preview.head(10))

App Store readable preview

,review_id,rating,title,content,updated_at,app_version,storefront,lang
0,14548034358,1,Liên tục lỗi không thể truy cập,"Là một người dùng lâu năm của tech, ban đầu rất hài lòng về chất lượng và giao diện của app, dễ giao dịch. Nhưng vài tháng trở lại đây app lỗi rất nhiều, chỉ đăng nhập có lúc đợi cả 5p vẫn chưa đăng nhập vào trang chủ được, thứ 2 là quảng cáo nhiều, truy cập vào được tài khoản thì phải tắt 7749 ...",2026-09-14T00:44:28-07:00,6.4.6,vn,unknown
1,14520064997,1,Tần suất bị lỗi mục tài sản quá nhiều,Rất hay bị lỗi báo k có tiền k có cổ phiếu nào trong tài khoản,2026-09-06T21:11:54-07:00,6.4.6,vn,unknown
2,14520054584,2,Khá tệ,"App rất lag, đôi khi còn không vào được",2026-09-06T21:07:12-07:00,6.4.6,vn,unknown
3,14504211053,3,Quá chậm,"Áp giao dịch gì mà chậm như rùa,mong bqt cải tiến",2026-09-02T20:32:43-07:00,6.4.6,vn,unknown
4,14468902446,1,Nghi vấn bán dữ liệu cho lái,"Tôi cầm cổ phiếu DBC 4 tháng, ngay khoảnh khắc khớp lệnh mua, cổ phiếu không một lần giá xanh, liên tiếp giảm 4 tháng liền. Tôi chấp nhận nạp tiền giữ vị thế margin, tuy nhiên sau 4 tháng, tôi muốn đổi cổ phiếu để có vị thế khác, ngay khoảnh khắc bán thì cổ phiếu DBC khớp lệnh và bay liên tiếp. ...",2026-08-24T21:00:51-07:00,6.4.4,vn,unknown
5,14467591535,5,NGUYEN VAN PHUONG,Namkuto,2026-08-24T12:29:06-07:00,6.4.4,vn,unknown
6,14465859621,1,"Giao diện rối khó sử dụng, CSKH kém, không thể gọi được NV CSKH","- UI UX kém, dễ bị bấm nhầm mua và bán\n- hotline chỉ để làm cảnh, AI trả lời tự động không giải quyết được vấn đề\n- không gọi được nv cskh, email không trả lời",2026-08-24T03:08:22-07:00,6.4.4,vn,unknown
7,14465018475,1,App lỗi quá nhiều,Nói chung quá tệ,2026-08-23T20:57:52-07:00,6.4.4,vn,unknown
8,14445501649,1,UI UX lởm quá,"UI UX này hoàn toàn ko phù hợp với iPad, chắc dev lười nên bê nguyên web sang. App chạy rất bất tiện, thao tác hoàn toàn lệch, ko hề chính xác. Dùng app thế này mà giao dịch thì lỗ nặng.",2026-08-18T22:09:21-07:00,6.4.4,vn,unknown
9,14439296592,1,Cách xác thực sự quá ngu,Lần đầu tiên tôi thấy việc xác thực để mở connection nhận data từ websocket nó ngớ ngẩn như vậy. Cứ 24 tiếng lại phải chạy vô app lấy cái OTP bằng tay xong đi cập nhật biến môi trường trước giờ giao dịch để k bị miss data. Đều đặn hằng ngày. Dev bên này nên thử mở cái docs của DNSE với SSi họ là...,2026-08-17T08:52:20-07:00,6.4.4,vn,unknown

Google Play readable preview

,reviewId,score,content,at,reviewCreatedVersion,appVersion,collection_locale
0,6638c299-2864-4386-837e-41064b75be48,1,sao cứ cứng đơ không nhích nhút gõ bất kỳ một chữ nào được....,2026-09-21 12:13:27,NaN,NaN,vi_vn
1,45b7bb0f-cd74-43a9-9b85-bd050b6a1f9f,1,Mới dùng thử . App giao diên quá chán. Dùng tcbs . Mà phải vào ssi xem giá . .ap quá chán luôn .,2026-09-21 05:51:18,6.4.5,6.4.5,vi_vn
2,4ae66065-e785-4516-a20d-51040c7a80d2,1,"rẻ rách, đã rườm rà còn khó xài",2026-09-18 18:49:22,6.4.5,6.4.5,vi_vn
3,f93f9a8e-c094-4ceb-8268-f4ba73dbb18c,1,"bắt làm chữ ký số mà cứ chụp ảnh xong là đơ, ko làm đc cái gì nữa, xóa đi cài lại vẫn thế",2026-09-15 22:04:51,6.4.5,6.4.5,vi_vn
4,ef9573f5-cac7-4b27-857a-f29bebf2c4d2,3,"Tôi đang sở hữu quỹ tcef đặt mua thêm ccq ngay trong tcef mà khi đặt lệnh lại lòi ra lệnh mua tcbf là sao vậy, ai code app kỳ vậy",2026-09-14 08:56:29,6.4.5,6.4.5,vi_vn
5,b60631dc-52f7-4a6e-ab62-777981d617ec,1,"Giao diện app quá tệ. Tính năng cơ bản như xem chart và đặt lệnh chuyển qua lại rất phức tạp, tôi muốn vừa xem chart nhanh vừa đặt lệnh nhiều ngày (24/7) đơn giản, mà app quá rườm rà, giao diện nhiều tính năng rác không dùng đến chiếm hết chỗ. Muốn xem danh mục của tôi đang giữ biến động thế nào...",2026-09-11 15:57:15,6.4.5,6.4.5,vi_vn
6,7d25eb7f-ac40-4de4-8943-5ab02a03cdbf,1,"App Techcombank Mobile nhanh bao nhiêu thì app TCBS chậm bấy nhiêu, đó là vì TCB mobile có giao diện đơn giản. Để cải thiện, các bạn cần đơn giản hóa giao diện, các cửa sổ lựa chọn chỉ nên hiện những gì cần thiết, cơ bản (các tính năng thông minh khác dành cho nhà đầu tư chuyên nghiệp nên được c...",2026-09-09 06:36:39,NaN,NaN,vi_vn
7,84a4e782-1615-4764-ad24-3974c5da8eb0,2,app lag giật khó dùng,2026-09-08 08:36:53,6.4.5,6.4.5,vi_vn
8,74c2b3de-07a9-4e83-afe4-76ce8134f8f0,1,"Rất tệ yêu cầu mã iOTP mà chờ gần 30p không có , liên hệ nhân viên thì không được , hệ thống quản lý quá kém",2026-08-29 21:30:32,6.4.5,6.4.5,vi_vn
9,5bac4bc7-ad1e-45fe-858c-84c7185e971a,1,"Ứng dụng lỏi, vô tạo tài khoản bấm tiếp tục mãi k đc",2026-08-28 23:10:48,6.4.14,6.4.14,vi_vn

## Random Review Sample

In [24]:
display(app_store_preview.sample(n=min(20, len(app_store_preview)), random_state=42))
display(google_play_preview.sample(n=min(20, len(google_play_preview)), random_state=42))

,review_id,rating,title,content,updated_at,app_version,storefront,lang
434,11737328061,5,Tuyệt vời,105CA18669,2024-09-18T05:47:47-07:00,5.7,vn,unknown
440,11737258935,5,Dễ sử dụng,"Giao diện app dễ sử dụng, đẹp",2024-09-18T05:26:06-07:00,5.7,vn,unknown
6,14465859621,1,"Giao diện rối khó sử dụng, CSKH kém, không thể gọi được NV CSKH","- UI UX kém, dễ bị bấm nhầm mua và bán\n- hotline chỉ để làm cảnh, AI trả lời tự động không giải quyết được vấn đề\n- không gọi được nv cskh, email không trả lời",2026-08-24T03:08:22-07:00,6.4.4,vn,unknown
184,13014069107,1,lỗi chuyển tiền,k rút tiền dc,2025-08-14T01:51:40-07:00,6.0.2,vn,unknown
78,13835758727,1,TK ng thân không nộp được tiền,"Mình tạo tk con, Lần 1 nộp bằng cú pháp khi nhấn nộp tiền trên áp, 2 ngày sau trả lại báo sai cú pháp, trong khi cú pháp tự đông gen ra\n\nLần này 4 ngày rồi không back lại tiền, mà back lại cũng k biết làm thế nào để nộp",2026-03-10T21:52:51-07:00,6.4.2,vn,unknown
299,12092046546,2,Phần đặt lệnh cổ phiếu thực sự chán. Đơn điệu không hiển được thông tin thị trường thời điểm đó.,"Nhiều lúc đặt giá xong mở ra xem giá tt đã thay đổi từ lúc nào. Phần đặt khối lượng cũng vậy, nhiều lúc quên ko biết khối lượng cp của mình có bao nhiêu lại phải quay lại từ đầu để xem. Thực sự rất khó chịu",2024-12-22T01:52:10-07:00,5.8.2,vn,unknown
521,9819441432,3,Hay bị lỗi app,Cứ vài ngày là lỗi app phãi xoá đi tải lại hoài.,2023-04-13T20:22:33-07:00,5.0.1,vn,unknown
484,11736926631,5,Dich vu tot,105CH90456,2024-09-18T03:24:09-07:00,5.7,vn,unknown
117,13630948771,1,Lỗi ai chịu,"Đang lỗi không giao dịch được, hãy sử lý và có lời giải thích thoả đáng. Lỗi hơn 1 tiếng chưa có trả lời khách hàng",2026-01-13T19:07:52-07:00,6.3,vn,unknown
137,13500073382,2,Biểu đồ kỹ thuật,Biểu đồ kỹ thuật chỉ cho xem theo hình dọc hoặc quay ngang thì không được full màn xem rất khó chịu. TCBS khắc phục thêm quả này nữa thì ngon,2025-12-10T22:23:18-07:00,6.2,vn,unknown
10,14425846977,1,"Làm ăn ko kỹ càng, cẩu thả","Các công ty đã rời sàn như HLG thì bị tcinvest loại luôn khỏi list, làm nhà đầu tư mất luôn thông tin số lượng cổ phiếu đang sở hữu. Ko thể nào biết để gặp cty HLG làm giấy xác nhận. Nhiều mã rời sàn như hiện nay thì mất rất nhiều. List tôi gồm 100 loại cổ phiếu nên ko nhớ được",2026-08-14T01:14:42-07:00,6.4.4,vn,unknown
508,11736883334,5,Oke,Ứng dụng tiện ích giúp chúng tôi kiểm soát đc tk bảo mật,2024-09-18T03:05:27-07:00,5.7,vn,unknown
75,13846427918,5,ap ok mà .còn được hay không thì do kiến thức và kinh nghiệm của bản thân,lúc đầu cũng tải nhiều app coi sao sau nhưng sau 1 thời gian lấy app này ổn định dùng luôn đc 5năm rồi,2026-03-14T01:27:26-07:00,6.4.2,vn,unknown
436,11737303426,5,105CH29389 tôi thích bảng giá,105CH29389 tôi thích bảng giá,2024-09-18T05:40:06-07:00,5.7,vn,unknown
476,11736971959,5,Ứng dụng tốt,105CH68998,2024-09-18T03:42:57-07:00,5.7,vn,unknown
140,13445903889,1,"Hỗ trợ AI quá kém, không giải quyết được vấn đề",Bộ phận hỗ trợ là AI hoạt động không hiệu quả. Chỉ dẫn theo các link có sẵn nhưng vẫn không giải quyết được vấn đề.,2025-11-26T23:07:30-07:00,6.2,vn,unknown
2,14520054584,2,Khá tệ,"App rất lag, đôi khi còn không vào được",2026-09-06T21:07:12-07:00,6.4.6,vn,unknown
155,13290348242,1,Không mua bán được trên TC Invest,"Ngày 20/10/2025 thị trường có phiên giảm sâu kỷ lục hơn 94 điểm, nhưng tôi không thể mua bán cổ phiếu trên app làm danh mục của tôi lỗ nặng do không thể mua để DCA",2025-10-20T03:02:17-07:00,6.1,vn,unknown
373,11739970007,5,Đánh giá 5 sao,"105CA67716 tôi thích bảng giá, giao dịch nhanh chóng, thuận lợi, cộng đồng đoàn kết. Very good!!!",2024-09-18T23:12:33-07:00,5.7,vn,unknown
131,13572173414,1,Thái độ nhân viên,Thái độ nhân viên chăm sóc khách hàng quá tệ,2025-12-30T01:22:52-07:00,6.3,vn,unknown

,reviewId,score,content,at,reviewCreatedVersion,appVersion,collection_locale
299,abff860a-3329-408e-a188-cf64dac8a665,1,"Ứng dụng rối nuồi khó sử dụng, lag, lỗi",2025-01-01 16:09:11,5.8.11,5.8.11,vi_vn
501,5db4f5b8-b014-46c1-ade1-9220e003ca81,1,Rối rắm. Khó dùng. Lag. Chậm. Nếu có 0 sao thì 1 sao cũng k xứng đáng,2024-08-02 09:27:56,NaN,NaN,vi_vn
631,08de7a4a-fecb-4600-a727-064057aee775,5,105C0910TA tôi thích bảng giá,2024-03-04 21:45:44,5.4.1,5.4.1,vi_vn
2098,9229dec5-3fce-4985-b83a-8b5da1fb7817,2,Lúc nào cũng gặp trục trặc với iOTP,2021-08-25 23:26:43,3.1.1,3.1.1,vi_vn
1377,b840a5c7-9bbb-4e6f-badd-e6c1fd2f5d4a,1,Cài hoài ko được,2022-04-26 19:56:17,NaN,NaN,vi_vn
1709,cc027484-9281-42c5-a44f-5bb297451ded,1,Ức chế những lúc thị trường điều chỉnh mạnh. Thích là không cho đặt lệnh. Buồn buồn là chơi lớn cấm cửa không cho giao dịch. Quá tệ.,2021-11-23 11:41:12,3.1.1,3.1.1,vi_vn
564,b9dac638-cc17-4d03-a456-ccf173c9464d,3,"Xoay ngang chưa được tốt lắm, dọc thì full màn, cần bổ sung thêm chỉ báo vào biểu đồ để có thể thuận tiện phân tích. Đa phần ở mức cơ bản",2024-04-03 00:17:36,5.5.2,5.5.2,vi_vn
1323,ed66daf9-cc37-4ec8-a2f0-a95c6580beb1,1,"App cực ngu, tìm kiếm, sao kê tài khoản, thực hiện margin tìm tất cả danh mục không thấy , sắp xếp rối tít mù . Mặc dù cũng dân công nghệ mà ko dùng nổi cái app này",2022-07-18 19:26:33,3.3.2,3.3.2,vi_vn
3060,d1e182cd-53a7-4a66-b8b1-de6afda48329,2,Please update app tobe able modify/cancel sell/buy command base on stock exchange. It should not lock all command on other stock like HNX UpCom,2021-06-10 15:01:54,3.0,3.0,en_vn
438,166a3e51-08f2-444f-adc9-edf731626ca0,5,Đâu tư tài chính,2024-08-16 07:59:48,5.7,5.7,vi_vn
2509,d59b0ef3-d05e-4e96-b35c-24777d3c893c,5,Ok,2020-10-09 01:53:38,NaN,NaN,vi_vn
871,7b9369ee-4dab-4d04-b86e-18e7893af68a,1,Hỗ trợ người dùng như cc,2023-10-20 11:07:01,5.1.3,5.1.3,vi_vn
2970,00193fc4-085c-4326-86cb-4221f68c58eb,3,"Lots of functionality bunched into one app makes TCBS a one-stop finance shop. However, technical issues are way too often including funds lockup today. Otherwise, 4.5star. Innovative & great potential.",2021-11-23 12:42:31,3.1.1,3.1.1,en_vn
1837,fd8b849e-938f-455e-80ac-8477b882fadb,1,Hôm nay tcbs lại thử thách tính kiên nhẫn của nđt. Ko đăt lênh được là thế nào nhỉ,2021-11-22 11:04:35,3.1.1,3.1.1,vi_vn
1116,e584f7a0-8925-4e26-9d93-3ff5c6a77fc2,1,"1 app lag và load chậm 2 năm nay ko cải thiện 2 giao diện bừa bộn thiếu khoa học 3 đặt lệnh tuy nhanh bố cục giao diện lỗi thời ,nhàm chán , khó sử dụng cho các lệnh khác nhau. 4 nạp và rút tiền còn lâu, nhất là rút khác ngân hàng . 5 HIỂN THỊ SAI GIÁ, SAI TÀI SẢN, SAI LỢI NHUẬN ...",2023-04-08 08:46:35,5.0,5.0,vi_vn
30,af8a59ca-c7f4-42e5-8334-271f9748bc89,5,Cải thiện UX/UI đơn giản nhưng nhiều chức năng sẽ tốt hơn.,2026-07-03 14:38:16,6.4.5,6.4.5,vi_vn
184,cae11e9b-ac4d-45ab-b66c-d68ac491a2d9,1,"Quá tệ, cho tiền vào đầu tư đến lúc rút tiền không cho xác thực tài khoản ngân hàng, liên hệ support thì toàn chát tự động, ko có nhân viên nào hỗ trợ, xác định mất",2025-08-15 16:28:02,6.1.2,6.1.2,vi_vn
2653,980f0ef8-74d0-4a90-b910-b08628916648,4,"App dạo này đặt lệnh hay nhảy linh tinh quá, điền mã CP xong điền giá thì mã CP lúc còn lúc ko, cảm giác rất khó chịu, trên web cũng tình trạng tương tự",2020-03-25 07:35:10,2.6.1,2.6.1,vi_vn
2276,6b93b5c7-9199-48e0-b279-5e6918137359,1,"Rất hay lỗi, ko hủy hay sửa lệnh đc, ko hiện giá trị.",2021-04-13 11:02:30,2.9,2.9,vi_vn
3192,696ac4f6-8230-4066-8807-08338e9ea827,1,"Ultra low performance. Switch tabs & menus is much slower than other apps. Even if entering OTP is not related the Internet, the app is slow and keep loading for nothing.",2020-03-16 20:06:22,2.6.1,2.6.1,en_vn

## Review by Rating

Change either variable to 1, 2, 3, 4, or 5. A rating is displayed as metadata and is not automatically interpreted as sentiment.

In [25]:
APP_STORE_RATING = 1
GOOGLE_PLAY_RATING = 1

app_rating_matches = app_store_preview[pd.to_numeric(app_store_preview["rating"], errors="coerce").eq(APP_STORE_RATING)]
google_rating_matches = google_play_preview[pd.to_numeric(google_play_preview["score"], errors="coerce").eq(GOOGLE_PLAY_RATING)]
print(f"App Store matches: {len(app_rating_matches):,}")
display(app_rating_matches.head(30))
print(f"Google Play matches: {len(google_rating_matches):,}")
display(google_rating_matches.head(30))

App Store matches: 217

,review_id,rating,title,content,updated_at,app_version,storefront,lang
0,14548034358,1,Liên tục lỗi không thể truy cập,"Là một người dùng lâu năm của tech, ban đầu rất hài lòng về chất lượng và giao diện của app, dễ giao dịch. Nhưng vài tháng trở lại đây app lỗi rất nhiều, chỉ đăng nhập có lúc đợi cả 5p vẫn chưa đăng nhập vào trang chủ được, thứ 2 là quảng cáo nhiều, truy cập vào được tài khoản thì phải tắt 7749 ...",2026-09-14T00:44:28-07:00,6.4.6,vn,unknown
1,14520064997,1,Tần suất bị lỗi mục tài sản quá nhiều,Rất hay bị lỗi báo k có tiền k có cổ phiếu nào trong tài khoản,2026-09-06T21:11:54-07:00,6.4.6,vn,unknown
4,14468902446,1,Nghi vấn bán dữ liệu cho lái,"Tôi cầm cổ phiếu DBC 4 tháng, ngay khoảnh khắc khớp lệnh mua, cổ phiếu không một lần giá xanh, liên tiếp giảm 4 tháng liền. Tôi chấp nhận nạp tiền giữ vị thế margin, tuy nhiên sau 4 tháng, tôi muốn đổi cổ phiếu để có vị thế khác, ngay khoảnh khắc bán thì cổ phiếu DBC khớp lệnh và bay liên tiếp. ...",2026-08-24T21:00:51-07:00,6.4.4,vn,unknown
6,14465859621,1,"Giao diện rối khó sử dụng, CSKH kém, không thể gọi được NV CSKH","- UI UX kém, dễ bị bấm nhầm mua và bán\n- hotline chỉ để làm cảnh, AI trả lời tự động không giải quyết được vấn đề\n- không gọi được nv cskh, email không trả lời",2026-08-24T03:08:22-07:00,6.4.4,vn,unknown
7,14465018475,1,App lỗi quá nhiều,Nói chung quá tệ,2026-08-23T20:57:52-07:00,6.4.4,vn,unknown
8,14445501649,1,UI UX lởm quá,"UI UX này hoàn toàn ko phù hợp với iPad, chắc dev lười nên bê nguyên web sang. App chạy rất bất tiện, thao tác hoàn toàn lệch, ko hề chính xác. Dùng app thế này mà giao dịch thì lỗ nặng.",2026-08-18T22:09:21-07:00,6.4.4,vn,unknown
9,14439296592,1,Cách xác thực sự quá ngu,Lần đầu tiên tôi thấy việc xác thực để mở connection nhận data từ websocket nó ngớ ngẩn như vậy. Cứ 24 tiếng lại phải chạy vô app lấy cái OTP bằng tay xong đi cập nhật biến môi trường trước giờ giao dịch để k bị miss data. Đều đặn hằng ngày. Dev bên này nên thử mở cái docs của DNSE với SSi họ là...,2026-08-17T08:52:20-07:00,6.4.4,vn,unknown
10,14425846977,1,"Làm ăn ko kỹ càng, cẩu thả","Các công ty đã rời sàn như HLG thì bị tcinvest loại luôn khỏi list, làm nhà đầu tư mất luôn thông tin số lượng cổ phiếu đang sở hữu. Ko thể nào biết để gặp cty HLG làm giấy xác nhận. Nhiều mã rời sàn như hiện nay thì mất rất nhiều. List tôi gồm 100 loại cổ phiếu nên ko nhớ được",2026-08-14T01:14:42-07:00,6.4.4,vn,unknown
12,14418152911,1,Quá phiền hà,"Phục vụ quá cứng nhắc thay số điện thoại, cccd bắt yêu cầu mở thẻ ngân hàng để xác minh thông tin.",2026-08-12T03:46:04-07:00,6.4.4,vn,unknown
13,14414751396,1,App như cặc,App như lol mỗi vào để điền thông tin xác thực thôi mà đen xì ko hiện ra 1 cái gì . Ngân hàng lớn mà thuê team IT trình độ kém quá,2026-08-11T07:10:45-07:00,6.4.4,vn,unknown
14,14409630266,1,"Tại sao lại giam tiền 2 hợp đồng, trong khi đã đóng vị thế trong cùng 1 ngày","10/08/2026 Tại sao lại giam tiền 2 hợp đồng, trong khi đã đóng vị thế trong cùng 1 ngày, các ngày khác không giam vẫn rút được bình thường chỉ trừ thuế phí, và vị thế đóng bị lỗ, rất thất vọng về TCBS",2026-08-10T00:58:38-07:00,6.4.4,vn,unknown
15,14381104681,1,"Ko rút tiền được, bị giam tiền","Ko đăng nhập được để rút tiền, lúc cần thì ko rút tiền được phải đi vay tiền nóng.",2026-08-02T20:15:17-07:00,6.4.4,vn,unknown
16,14354074084,1,Bảo mật ngou như con bò,Dcmm xoá đi tải lại thì bắt xác nhận đăng nhập iotp trên máy đã đăng kí trc đó trong khi dùng đúng máy đó nhưng lại k cho đăng nhập vào dcm code ngoulol,2026-07-27T05:11:15-07:00,6.4.4,vn,unknown
17,14352635121,1,App lỗi rất nhiều lần,"App hay bị lỗi quay vòng vòng chờ dữ liệu, rồi lâu lâu đặt lệnh thì không được rất bực mình, tỷ lệ lỗi rất nhiều",2026-07-26T19:35:18-07:00,6.4.4,vn,unknown
18,14352633073,1,Không có nhân viên hỗ trợ,Dịch vụ kém,2026-07-26T19:34:31-07:00,6.4.4,vn,unknown
20,14313162800,1,Giam Tiền cổ tức,App này chuyên giam Tiền cổ tức đợi cuối ngày hết giao dịch mới nhả Tiền ra trong khi công ty chứng khoán khác Tiền đã về để cho giao dịch trong phiên.,2026-07-16T23:45:43-07:00,6.4.4,vn,unknown
21,14296658625,1,App rất thường bị lỗi,Rất thường gặp lỗi đăng nhập,2026-07-12T21:19:17-07:00,6.4.4,vn,unknown
23,14223394760,1,App tệ,"App rắc rối. Rất khó dùng. Nhiều mục không cần thiết cho nđt mà cũng chưng hết ra, rối rắm.\nCực kỳ khó dùng so với các app chứng khoán khác như của Ssi, vnd, vps.\nTôi đã dùng nhiều app khác rồi mà dùng app Tcbs này thực sự rất bực mình luôn.",2026-06-24T22:43:41-07:00,6.4.4,vn,unknown
25,14149839961,1,Cái ipower lúc ẩn lúc hiện như ma,Lúc cần rút tiền thì tính năng ipower bị biến mất không rút tiền được,2026-06-06T01:12:27-07:00,6.4.4,vn,unknown
26,14147186413,1,Ứng dụng hệ thống như một tên bịp bợm.,Chức năng “ứng tiền trước” giờ có giới hạn dù mình không dùng chức năng này đã lâu.\nVà nợ phí lưu ký thì không tự động trừ tiền dù có liên kết tài khoản hay đã nạp tiền. Nợ đó cứ bị tính lãi cao lên như ăn cướp vậy. Dịch vụ chỉ muốn cướp đoạt tài sản của người khác. Không nên dùng.,2026-06-05T08:28:37-07:00,6.4.4,vn,unknown
27,14142865973,1,Ai như tôi không nạo tiền vào không lâu tiền bay hết sạch,Chắn,2026-06-04T06:07:36-07:00,6.4.4,vn,unknown
29,14051715882,1,Quá tệ cho 1 sàn do ngân hàng đầu ngành vận hành,Tiền phong tỏa khi hủy lệnh rất chậm trong khi lệnh hủy từ 3 4 tiếng trước. Quá tệ cho 1 sàn chứng khoán được vận hành bởi ngân hàng lớn.,2026-05-11T00:18:29-07:00,6.4.3,vn,unknown
31,14040031598,1,1 vấn đề gặp hoài mà ko xử lý,"Dạo gần đây nđt bán cp ko ứng tiền được và lỗi chuyển tiền ra ngoài ko vào tk kh, khách hàng phải chat với tư vấn viên nhưng chả giải quyết đc vấn đề, tiền với nđt rất quan trọng nhưng tcbs muốn đuổi khách rồi",2026-05-07T19:14:26-07:00,6.4.3,vn,unknown
33,14033216115,1,App ngày càng tệ!,"App bị đơ, hiển thị thông tin sai, không có ai thấy bug để fix hết hay sao ấy",2026-05-05T21:15:56-07:00,6.4.3,vn,unknown
34,14009628721,1,Lỗi hiển thị sai giá ko thể mua bán,App lỗi tệ,2026-04-29T08:34:18-07:00,6.4.3,vn,unknown
35,14008131020,1,App lỗi không giao dịch được.,"App lỗi tê liệt ngay đầu phiên giao dịch. Bảng điện không cập nhật, không mua bán được. Làm mất tiền và cơ hội của nhà đầu tư. Không nên dùng app này.",2026-04-28T22:12:10-07:00,6.4.3,vn,unknown
36,14007852344,1,App lỏ xứng đáng 1 sao,"App sập, đơ, k giao dịch đc. TCBS phải đền bù cho khách đi!!!",2026-04-28T19:52:45-07:00,6.4.3,vn,unknown
37,14007849446,1,Tệ,Quá tệ. Cập nhật gì vào lúc 9h15. Chốt lời k được luôn. Thiệt hại vậy ai chịu. Bực bội,2026-04-28T19:51:24-07:00,6.4.3,vn,unknown
38,14007848369,1,"App đơ, web đơ, rất rất tệ","App đơ, web đơ, rất rất tệ",2026-04-28T19:50:53-07:00,6.4.3,vn,unknown
39,14007846536,1,Lỗi app 29/04/2026,Bảng điện đứng im app hiện toàn bộ dữ liệu của 28/04. NĐT nhìn tài khoản mà khóc ròng. Liệu TCBS sẽ có bồi hoàn gì hay chỉ là Xin Lỗi khi tiền NĐT bay theo lỗi app,2026-04-28T19:50:03-07:00,6.4.3,vn,unknown

Google Play matches: 1,799

,reviewId,score,content,at,reviewCreatedVersion,appVersion,collection_locale
0,6638c299-2864-4386-837e-41064b75be48,1,sao cứ cứng đơ không nhích nhút gõ bất kỳ một chữ nào được....,2026-09-21 12:13:27,NaN,NaN,vi_vn
1,45b7bb0f-cd74-43a9-9b85-bd050b6a1f9f,1,Mới dùng thử . App giao diên quá chán. Dùng tcbs . Mà phải vào ssi xem giá . .ap quá chán luôn .,2026-09-21 05:51:18,6.4.5,6.4.5,vi_vn
2,4ae66065-e785-4516-a20d-51040c7a80d2,1,"rẻ rách, đã rườm rà còn khó xài",2026-09-18 18:49:22,6.4.5,6.4.5,vi_vn
3,f93f9a8e-c094-4ceb-8268-f4ba73dbb18c,1,"bắt làm chữ ký số mà cứ chụp ảnh xong là đơ, ko làm đc cái gì nữa, xóa đi cài lại vẫn thế",2026-09-15 22:04:51,6.4.5,6.4.5,vi_vn
5,b60631dc-52f7-4a6e-ab62-777981d617ec,1,"Giao diện app quá tệ. Tính năng cơ bản như xem chart và đặt lệnh chuyển qua lại rất phức tạp, tôi muốn vừa xem chart nhanh vừa đặt lệnh nhiều ngày (24/7) đơn giản, mà app quá rườm rà, giao diện nhiều tính năng rác không dùng đến chiếm hết chỗ. Muốn xem danh mục của tôi đang giữ biến động thế nào...",2026-09-11 15:57:15,6.4.5,6.4.5,vi_vn
6,7d25eb7f-ac40-4de4-8943-5ab02a03cdbf,1,"App Techcombank Mobile nhanh bao nhiêu thì app TCBS chậm bấy nhiêu, đó là vì TCB mobile có giao diện đơn giản. Để cải thiện, các bạn cần đơn giản hóa giao diện, các cửa sổ lựa chọn chỉ nên hiện những gì cần thiết, cơ bản (các tính năng thông minh khác dành cho nhà đầu tư chuyên nghiệp nên được c...",2026-09-09 06:36:39,NaN,NaN,vi_vn
8,74c2b3de-07a9-4e83-afe4-76ce8134f8f0,1,"Rất tệ yêu cầu mã iOTP mà chờ gần 30p không có , liên hệ nhân viên thì không được , hệ thống quản lý quá kém",2026-08-29 21:30:32,6.4.5,6.4.5,vi_vn
9,5bac4bc7-ad1e-45fe-858c-84c7185e971a,1,"Ứng dụng lỏi, vô tạo tài khoản bấm tiếp tục mãi k đc",2026-08-28 23:10:48,6.4.14,6.4.14,vi_vn
10,9450f8ac-d9ba-4f47-b7f2-3271066a7707,1,app lỗi vcl. không quay vid xác thực khuôn mặt được. quá tệ,2026-08-25 10:25:19,6.4.5,6.4.5,vi_vn
13,b80c2d64-7ce6-4036-9237-860697ee5178,1,"chậm, lag quá ạ",2026-08-12 15:23:48,6.4.5,6.4.5,vi_vn
15,01ad6ded-2aab-45a5-b0c7-e94d5828b921,1,lag,2026-08-07 09:24:22,6.4.1,6.4.1,vi_vn
16,e5ec7f53-687e-43a7-aa2c-55e6ead04049,1,"App quá chán. Lúc cần bán thì k vào dc, dựt lag quá",2026-08-04 20:07:41,6.4.5,6.4.5,vi_vn
18,02cf4533-f984-4fee-9f9a-dfcca55f1a06,1,Tạo tài khoản không cho tạo r hiện sđt không hợp lệ?? Vậy tạo app chi mà không cho người dùng giao dịch??,2026-07-29 21:49:39,6.4.5,6.4.5,vi_vn
22,e7a9cf27-0878-42f7-8972-3a2542c2af3f,1,"phần mềm tồi tệ, xác minh khuôn mặt cả nghìn lần không được.",2026-07-15 08:11:02,NaN,NaN,vi_vn
23,1eb01879-8d2e-41ce-a4b4-1dfd9c6ffd53,1,"App lag, lỗi lurg tung, liên kết TCB gì mãi chả được, số dư thì hiện chập chờn Bó tay",2026-07-11 12:10:10,6.4.5,6.4.5,vi_vn
24,8a6e6c41-9bfb-4a15-bbae-c2f83ead1bda,1,"phí rẻ nên xài. nhưng quản lý lời lỗ phải nhờ excel, xem bảng giá phải nhờ SSI. nói chung được mỗi cái phí rẻ. app lởm quá.",2026-07-09 14:51:45,NaN,NaN,vi_vn
25,0965c4ed-df13-48d6-b0f0-8f5c739800da,1,"không xác nhận được sinh trắc học, lúc nộp video nó load gần 1h không xong phần submitting the vertification, không đăng ký được",2026-07-09 11:24:32,6.4.5,6.4.5,vi_vn
26,acf31f80-cf4c-44e3-b70e-0245cf368521,1,không cài đặt được vân tay,2026-07-07 11:15:04,6.4.5,6.4.5,vi_vn
27,80e560a0-ba66-4116-9e4a-6140ea9cbe79,1,"App rất tệ, không thể chuyển tiền từ TCBS ra ngân hàng",2026-07-06 22:08:46,6.4.5,6.4.5,vi_vn
28,89c58827-2128-479a-bdfa-12cb8375f846,1,chuyển tiền buổi tối khi cần thiết không cho chuyển,2026-07-06 21:14:56,6.4.5,6.4.5,vi_vn
29,237cc17c-8b8a-4adf-9882-de55eb411a19,1,áp nhìn rối mắt khó xài quá nên đổi cho dể nhìn dể thao tác,2026-07-06 10:57:17,6.4.5,6.4.5,vi_vn
31,83d82a5a-a7ff-4496-8ce4-6e2b34d70397,1,"Rác vãi, lỗi lên lỗi xuống thế thì làm sao có người dùng",2026-06-30 18:08:47,6.4.5,6.4.5,vi_vn
32,9e0c556c-b2cf-4748-b15d-39495f996bf3,1,không chạy nổi,2026-06-30 15:47:12,6.4.5,6.4.5,vi_vn
34,e3383658-6e3a-42cd-9016-5563a4a31347,1,"cực kỳ đơ lag giật. giao diện không thân thiện. UI Ux tệ, dễ đặt nhầm lệnh. bấm vào phần đặt giá thì bàn phím ảo hiện lên che hết giá dẫn đến vào giá sai. k lưu đc indicator",2026-06-29 11:18:00,6.4.5,6.4.5,vi_vn
35,eb419b10-baf3-404a-b6ec-828b0eee758c,1,"không thể cài vân tay, vấn đề ở đâu vậy?",2026-06-26 10:25:50,6.4.5,6.4.5,vi_vn
38,2e57ca2a-a55a-4673-aaf5-c000e60ed58f,1,"app tệ hại. chất lượng dịch vụ kém. tổng đài trả lời rất chậm, vô trách nhiệm.",2026-06-25 10:00:03,6.4.5,6.4.5,vi_vn
40,1b8d554a-8ac2-466c-9a62-48d2ceb8f9dc,1,"Có mỗi chuyện đổi sdt thông tin khách hàng thôi mà 3 tuần không xong, trong khi là nội bộ xử lý xử lý sai quy trình bắt khách hàng chịu",2026-06-15 14:41:15,6.4.5,6.4.5,vi_vn
41,b431f770-1878-4782-99ba-23a4eadeb8a8,1,có mỗi iotp mà nửa ngày không thấy gửi. tốn thời gian,2026-06-15 12:31:37,6.4.5,6.4.5,vi_vn
42,4c428c82-6ec9-4e1e-b37f-4e6ef8b5f482,1,me nó bán kiểu gì deo được vậy,2026-06-07 16:17:47,6.4.5,6.4.5,vi_vn
44,c94d9d46-d3f6-4d2b-a423-99fd466da2bf,1,"ứng dụng lag lỏ , lỗi ngay từ đăng nhập , lỗi vân tay đen màn hình",2026-06-05 09:00:28,6.4.5,6.4.5,vi_vn

## Keyword Search

Examples: `đăng nhập`, `otp`, `chậm`, `lag`, `rút tiền`, `mua`, `bán`, `giao diện`, `phí`, `hỗ trợ`. Search results are not classifications.

In [26]:
KEYWORD = "đăng nhập"

app_search_text = app_store_df["title"].fillna("").astype(str) + " " + app_store_df["content"].fillna("").astype(str)
app_keyword_matches = app_store_preview[app_search_text.str.contains(KEYWORD, case=False, na=False, regex=False)]
google_keyword_matches = google_play_preview[google_play_df["content"].str.contains(KEYWORD, case=False, na=False, regex=False)]
print(f"App Store keyword matches for {KEYWORD!r}: {len(app_keyword_matches):,}")
display(app_keyword_matches.head(50))
print(f"Google Play keyword matches for {KEYWORD!r}: {len(google_keyword_matches):,}")
display(google_keyword_matches.head(50))

App Store keyword matches for 'đăng nhập': 14

,review_id,rating,title,content,updated_at,app_version,storefront,lang
0,14548034358,1,Liên tục lỗi không thể truy cập,"Là một người dùng lâu năm của tech, ban đầu rất hài lòng về chất lượng và giao diện của app, dễ giao dịch. Nhưng vài tháng trở lại đây app lỗi rất nhiều, chỉ đăng nhập có lúc đợi cả 5p vẫn chưa đăng nhập vào trang chủ được, thứ 2 là quảng cáo nhiều, truy cập vào được tài khoản thì phải tắt 7749 ...",2026-09-14T00:44:28-07:00,6.4.6,vn,unknown
15,14381104681,1,"Ko rút tiền được, bị giam tiền","Ko đăng nhập được để rút tiền, lúc cần thì ko rút tiền được phải đi vay tiền nóng.",2026-08-02T20:15:17-07:00,6.4.4,vn,unknown
16,14354074084,1,Bảo mật ngou như con bò,Dcmm xoá đi tải lại thì bắt xác nhận đăng nhập iotp trên máy đã đăng kí trc đó trong khi dùng đúng máy đó nhưng lại k cho đăng nhập vào dcm code ngoulol,2026-07-27T05:11:15-07:00,6.4.4,vn,unknown
21,14296658625,1,App rất thường bị lỗi,Rất thường gặp lỗi đăng nhập,2026-07-12T21:19:17-07:00,6.4.4,vn,unknown
59,13987803897,1,Đăng nhập lỗi,Đăng nhập toàn quay. Không vào được app,2026-04-23T01:17:00-07:00,6.4.3,vn,unknown
68,13884487026,1,Lỗi,Widget bị lỗi phiên đăng nhập đã hết hạn dù đã đăng nhập rồi. Thường xuyên bị lỗi vừa mở app đã bị dừng đột ngột,2026-03-24T23:45:50-07:00,6.4.3,vn,unknown
99,13714566655,1,Cá con,App chán toàn đơ lag lúc cao điểm giờ thêm bảo trì vào thời gian gd. Giam chân nđt.\nMua điện thoại mới đăng nhập không được mặc dù có số tk và mật khẩu và Sdt chính chủ rồi. Bắt xác nhận điện thoại cũ (đã cho và đã cài lại máy và người nhận cũng đã đi xa) rất bất tiện. Vậy trường hợp mất máy th...,2026-02-04T22:19:24-07:00,6.4.1,vn,unknown
127,13628373156,1,Giao diện xấu,"App giao diện xấu, rất khó hiểu, quy trình đăng nhập rườm rà gây trải nghiệm người dùng ko tốt. Nên thuê UX designer xây lại app giống app Techcombank",2026-01-13T03:50:01-07:00,6.3,vn,unknown
176,13068775356,1,Còn cần cải thiện,"Đăng nhập trên XS Max lại hiện option vân tay, nghĩ nó chán",2025-08-27T19:14:25-07:00,6.0.2,vn,unknown
279,12387003343,1,Lỗi đăng nhập - gọi hỗ trợ chỉ có tổng đài tự động,Hỗ trợ kém,2025-03-05T19:00:38-07:00,5.8.5,vn,unknown
285,12316968970,4,Lỗi đăng nhập,Không đăng nhập được bằng Face ID trên iPhone 11. Mong đội ngũ phần mềm khắc phục được lỗi này,2025-02-16T00:26:56-07:00,5.8.5,vn,unknown
317,11813796447,1,Bảo mật không có,"Version hiện tại có thể đăng nhập tự do, không cần nhập mật khẩu hoặc face ID - trong cả 2 trường hợp cài đặt dùng face ID để đăng nhập và không dùng. \nBảo mật quá lỏng lẻo.",2024-10-09T01:01:19-07:00,5.8,vn,unknown
324,11779920813,2,Lỗi,"Sáng nay đăng nhập đơ, không vào được.",2024-09-29T19:34:20-07:00,5.8,vn,unknown
332,11750539058,4,Cần cải thiện,"Phần đăng nhập & các bước thực hiện nhanh , thuận lợi\nTuy nhiên có các phần cần khắc phục\n+ Đợt vừa rồi ở phần tất cả không hiện thị thông số tiền trong 2 TK ngân hàng và tk ký quỹ ( bảng all )\n+ Margin không hiển thị + -",2024-09-21T19:23:34-07:00,5.7,vn,unknown

Google Play keyword matches for 'đăng nhập': 82

,reviewId,score,content,at,reviewCreatedVersion,appVersion,collection_locale
44,c94d9d46-d3f6-4d2b-a423-99fd466da2bf,1,"ứng dụng lag lỏ , lỗi ngay từ đăng nhập , lỗi vân tay đen màn hình",2026-06-05 09:00:28,6.4.5,6.4.5,vi_vn
66,9affbb8e-9af2-4acd-945b-ddcac4ea8907,1,"2 hôm nay ko thể vào đc, cứ bị văng ra ko cho đăng nhập, quá tệ",2026-04-17 10:07:15,6.4.1,6.4.1,vi_vn
72,8601f3eb-e66c-468b-a6cc-f536335533e3,1,16.04.2026 đăng nhập liên tục mà không vào được gọi điện thoạ gần 10 cuộc cũng không được nhắn tin thì cho con AI ngoo ngốc trả lời. khó hiểu thật sự,2026-04-16 12:13:29,6.4.1,6.4.1,vi_vn
73,c5d09130-930e-454b-9af7-fda1b6a1da19,2,lỗi ko đăng nhập dc.,2026-04-16 10:11:05,6.4.1,6.4.1,vi_vn
75,ade96f2c-c95d-4486-8c9b-17394d3bd7e7,3,bị lỗi out khi đăng nhập samsung note s23 ultra,2026-04-16 08:45:49,6.4.1,6.4.1,vi_vn
98,bd9c1fa8-0b6c-4eca-a793-693a8fe25c9a,1,ứng dụng tồi. từ tết đến giờ k đăng nhập nổi,2026-02-24 22:37:40,6.4.1,6.4.1,vi_vn
101,e848fbee-1472-45b5-a050-7ebe95952516,1,ngày 10.02.2026 lỗi không đăng nhập được,2026-02-11 06:22:22,6.4.1,6.4.1,vi_vn
110,2e5b19b6-95a6-4096-a902-97b2962bf652,1,đăng nhập gì mà lỗi riết à,2026-01-24 23:13:13,6.4.1,6.4.1,vi_vn
150,5e10e799-e923-496b-818d-fb89540ed690,1,"đăng nhập rồi lỗi, không dùng được",2025-10-17 09:22:00,3.3.3,3.3.3,vi_vn
268,74be1267-4cc5-42d7-ad3d-6a7fc5212b86,1,"Quay như chong chóng, k đăng nhập được",2025-03-02 17:09:37,5.8.15,5.8.15,vi_vn
269,5dd0f3f0-4aa9-473c-9c6f-ac1a156c50b6,1,T không đăng nhập được trên note 8,2025-02-24 21:12:02,3.3.3,3.3.3,vi_vn
279,ad76edd9-a952-4969-8e45-ef221d81f18b,1,Ko quét đc QR để đăng nhập trên máy tính. Nhiềi popup tắt đi rồi vẫn hiện,2025-02-05 15:16:18,5.8.12,5.8.12,vi_vn
287,bdc43597-7227-4f14-a0f8-c8eba93ef177,1,"App ngu vô cùng ngu Sau khi tạo tài khoản thì không cho đăng nhập nữa ủa alo vậy thì sao dùng ????? Liên hệ CSKH thì nói chuyện như bot, không có chuyên môn, qua loa, bắt đăng nhập trên app đt trên web máy tính, đổi wifi 4g mở tab ẩn danh vẫn không được Rồi xin teamview vào laptop cá nhân ??? Ơ ...",2025-01-23 12:52:48,5.8.12,5.8.12,vi_vn
407,b080ef32-8c73-4406-9b96-6eba1a1c3a02,5,"Ứng dụng rất tốt, đăng nhập, đặt lệnh, hủy lệnh, sửa lệnh rất nhanh, danh mục trong ứng dụng đa dạng đầy đủ, và nhiều chức năng hữu ích khác nữa.",2024-09-18 16:08:19,5.7.2,5.7.2,vi_vn
454,dbc2a2fa-9dc9-465b-9f19-cfc99afb6869,1,"Nhiều qc rác, vào app tự load lại 10 lần ms hiện ra đăng nhập vân tay",2024-08-15 01:00:18,5.7,5.7,vi_vn
496,eeeb0015-20ff-4a2d-88a2-7c0121be18ef,1,"App bị lỗi không đăng nhập được,gỡ app xong cài lại bắt ĐK iotp rất mất thời gian,sau khi ₫k xong tối lại lỗi không đăng nhập được.Quá tệ.",2024-08-14 00:30:13,5.7,5.7,vi_vn
498,2c173753-5450-416b-95f1-adcfdfbfe0b9,1,Ứng dụng bắt xóa bộ nhớ đệm và liên tục không đăng nhập được.,2024-08-12 14:58:15,5.6.5,5.6.5,vi_vn
572,ed024b99-15c1-4c97-9958-a9e721c9f380,1,App chậm không đăng nhập được,2024-03-22 09:30:40,5.4.1,5.4.1,vi_vn
578,4d5be425-fbea-4220-87ba-83636ac12764,1,Chán thật sự Đăng nhập mãi ko được,2024-03-18 19:37:59,5.4.1,5.4.1,vi_vn
580,587cf22d-1e28-4570-8b19-f2a150c2492f,2,"Nạp tien vào tk rất lâu. Tiền trong tk lúc hiện lúc ko. Đặt lệnh ko có khối lượng max. Toàn mò khối lượng, hay phải tính nhân để biết sức mua của mình bao nhiêu.Thoát ra không bị đăng nhập lại. Đăng nhật dễ dàng. Tùy chỉnh giao diện theo sở thích người dùng",2024-03-18 18:38:17,5.4.1,5.4.1,vi_vn
581,3db609fa-c4be-46ee-9bc2-0dac30eb0ab1,1,bị lỗi không đăng nhập được,2024-03-18 18:22:52,5.4.1,5.4.1,vi_vn
582,772a7bd6-e82f-47f6-ad0b-7666c7f96079,1,"App lỗi vãi, đăng nhập mãi không được",2024-03-18 17:54:21,5.4.1,5.4.1,vi_vn
584,ba52df41-2eb6-426e-a86c-44b046286326,1,"Nhà phát hành nên sửa lỗi về hệ thống xử lí. Tốc độ xử lí quá chậm, tôi đã đăng nhập vào chờ rất lâu nhưng không có phản hồi từ app.",2024-03-18 17:06:55,5.4.1,5.4.1,vi_vn
990,d829dae8-9106-4b72-b51b-884366ec4a7b,1,"Buồn, không thể đăng nhập và giao dịch được, cứ yêu cầu mk đăng nhập để cài iOTP giao dịch, dì nhập đúngvnh lần vẫn không đc, vẫn tính sai đợi xang ngày mới đăng nhập lại. Lien lạc trợ giúp cũng chẳng thành. Quá chán.",2023-08-10 13:03:21,5.1.1,5.1.1,vi_vn
1247,1446f46f-ba44-4f44-b83a-e954b4a76d49,1,"App ngu vl. Đăng ký từ app techcom, qua app này đăng nhập kiểu gì cũng báo sai",2022-10-28 14:56:52,3.3.5,3.3.5,vi_vn
1309,9fe51950-89e6-4655-bc30-d803134f3432,1,Sao tôi k thể đăng nhập đc,2022-08-13 19:39:08,NaN,NaN,vi_vn
1391,5e01a70b-db0e-4359-ab7a-48fcf196cec5,1,"Suốt ngày lỗi, k đăng nhập để giao dịch được",2022-03-30 13:08:59,3.1.1,3.1.1,vi_vn
1456,0846150a-737e-4205-917f-b411745f9f36,1,Ứng dụng tệ hại .app lỗi ko đặt lệnh được Liên tục. Số liệu bảng giá ko khớp giữa 2 ngày mặc dù có chiều qua đóng của giá khác sáng vẫn giá vàng nhưng giá lại khác giá đóng cửa hôm qua. Đăng nhập quay vòng vòng ko vào được ảnh hưởng đến việc đầu tư của nhà đầu tư. Cập nhật thông tin cổ tức. Tiền...,2022-01-28 10:52:53,3.1.1,3.1.1,vi_vn
1462,8ece7446-202e-4267-b9df-482ac6f55f13,2,App đăng nhập quá chậm. Bố cục rối rắm. Quá nhiều thứ linh tinh,2022-01-21 15:47:59,3.1.1,3.1.1,vi_vn
1699,10541b1c-122f-487c-a3b8-3881f761c965,2,"Rate 2 sao vì thích giao diện của tcbs và giải thích trong các danh mục khác nhau , có 1 số lỗi mà tôi đã gặp. 1) ko thể đăng nhập đc dù trên app hay web 2) ko thể sửa lệnh 3) ko được phép giao dịch 4) hiển thị sai giá trị cổ phiếu ở danh mục tài sản 5) hay bị đơ khi ở phiên giao dịch - Mong đội...",2021-11-23 11:56:02,3.1.1,3.1.1,vi_vn
1787,ee1aeba4-80f5-4d92-b0e9-6e2221112901,1,"App thiếu ổn định quá, hay lỗi đăng nhập và cập nhật dữ liệu, Cứ đến ngày thị trường biến động là App lại đơ, lại sự cố, Công ty chứng khoán mà liên tục cập nhật nhưng vẫn lỗi hàng ngày. Xin lỗi thôi là xong sao.",2021-11-23 10:40:54,NaN,NaN,vi_vn
1903,6f815ebf-4770-44a9-84bf-0050ecc2a1dd,1,"Đến giờ đăng nhập không cho Đăng nhập gây thất thoát tiền của của nhà đầu tư , đây là lần thứ bao nhiêu rồi ? Đừng giải thích gì khi mà các công ty khác họ không bị.chia tay thôi không cháy tài khoản mất.liệu có mờ ám gì phía sau ?",2021-11-03 23:38:19,3.1.1,3.1.1,vi_vn
1942,7e3422e1-a8fd-4662-8890-44f0adfcd8e5,1,"Lỗi khi đăng nhập, giao dịch chậm, ảnh hưởng trải nghiệm người dùng",2021-11-03 15:00:20,3.1.1,3.1.1,vi_vn
1960,4649da59-c240-4831-940d-9a7d6540b51b,1,"Hiện tại là 11h ngày 3/11, lệnh đã đặt được bình thường sau khi thì trường sập. Điều này chứng tỏ tcbs cố tình chặn đăng nhập của nhà đầu tư để đội tự doanh của mình chốt lời trước. Mọi người không nên giao dịch với công ty không minh bạch thế này, và nên vào link thanh tra chính phủ đề nghị tha...",2021-11-03 11:05:01,3.1.1,3.1.1,vi_vn
1971,2dbcb9f7-5ce8-43f2-9425-d2862b2696ea,1,Quá tệ! Giờ giao dịch k đăng nhập đc!,2021-11-03 10:39:38,NaN,NaN,vi_vn
1978,6efc4b0a-a2b0-4a7d-8e4c-5be294690d18,1,"App suốt buổi sáng hôm nay 3/11 không đăng nhập vào được, làm lỡ cơ hội vào cổ phiếu giá tốt. Dùng qua 3 app VND, VPS, TCBS thì cái TCBS này tệ nhất gián tiếp làm mất tiền nhà đầu tư.",2021-11-03 10:29:44,3.1.1,3.1.1,vi_vn
2004,9db827a1-1ab2-4ef3-8c7e-5e0ee1cc136c,1,"Từ vps qua tcbs trải nghiệm,lỗi k đăng nhập đc trên web với app. Từ giá hạ đến giá tăng vẫn k vô đc để đặt lệnh :v",2021-11-03 10:03:54,3.1.1,3.1.1,vi_vn
2005,28c26b8d-451b-49e0-9844-8ececf4529a6,1,App chán quá đăng nhập mãi không vào đc mất hết hàng,2021-11-03 10:02:40,3.1.1,3.1.1,vi_vn
2016,aaa8debc-3a95-4ed6-a37d-6987a788f2b7,2,"App và website thường bị treo, ko thể đăng nhập cũng như giao dịch.",2021-11-03 09:50:16,3.1.1,3.1.1,vi_vn
2031,82995d73-60d5-4677-8c90-a4c0d42abdff,1,Không đăng nhập được. Lỡ cơ hội của nhà đầu tư,2021-11-03 09:36:14,3.1.1,3.1.1,vi_vn
2033,baba4488-0214-415a-a98f-065c4d116578,1,Hôm nay 3/11/2021 không đăng nhập được vậy ảnh hưởng rất nhiều đến nđt,2021-11-03 09:33:11,NaN,NaN,vi_vn
2038,02bbf848-2761-4554-af93-0298244e61cc,1,Ứng dụng thường xuyên bị lỗi. Không đăng nhập được để đặt lệnh.,2021-11-03 09:32:03,3.1.1,3.1.1,vi_vn
2042,292f25ca-fd44-4978-961a-4e11edb9d52e,1,Quá tệ. Khi cần đăng nhập giao dịch thì cả app cả trên laptop đều không đăng nhập được. Thiệt hại này ai chịu cho người dùng. Thực sự khó chịu,2021-11-03 09:27:59,3.1.1,3.1.1,vi_vn
2043,c88bc5c7-af36-4764-a7aa-bd1f59cecc23,1,"App khốn kiếp, lúc quan trọng thì không đăng nhập được. Đừng ai dùng của bọn này nhé",2021-11-03 09:26:17,3.1.1,3.1.1,vi_vn
2056,12367da1-f7c9-44c1-ac42-22e32d93a4bb,3,Hiển thị của chỉ số VNI trên giao diện bảng giá thường xuyên bị che lấp về bên trái khi trải nghiệm trên điện thoại. Cài đặt lại ap thì được nhưng khi thoát ra đăng nhập lại thì vẫn bị. Rất khó chịu khi theo dõi chỉ số VNI.,2021-10-29 16:30:28,3.1.1,3.1.1,vi_vn
2070,a45eb629-6b67-4541-be17-8fdb8c5a0086,4,Sau khi đăng nhập hay bị reload. Dùng không mượt lắm,2021-10-05 21:34:43,3.1.1,3.1.1,vi_vn
2134,a4b7b2e6-1b25-404f-8c23-8266c47643e7,1,App đổi giao diện liên tục. Không cho sử dụng giao diện destop trên máy tính bảng khi xoay màn hình. Hôm nay cài bản mới thì ko thể vào phần cài đặt để đăng nhập bằng vân tay. Càng đổi mới càng tệ. Rate 1☆.,2021-07-27 08:13:10,3.0,3.0,vi_vn
2138,a1aebeb9-0ced-426a-9121-88a690a598cf,1,"Áp có tính bảo mật KHÔNG cao, tắt hết rồi bật lại thì vẫn đang đăng nhập như fb ý, phải tự thoát ra, mà tài khoản chứng khoán là tiền thật chứ có phải tiền chơi chơi đâu, chuyển tiền từ tk ngân hàng sang ứng dụng rất lâu, phần phân tích trông có vẻ rất chi tiết thế nhưng rất rối mắt, danh sách c...",2021-07-22 22:13:31,3.0,3.0,vi_vn
2207,dc9773df-bd88-4b3d-a4a7-f28990765281,1,"Hệ thống rất không ổn định, nhiều lúc không thể đăng nhập cũng không thể vào lệnh",2021-06-07 09:41:33,NaN,NaN,vi_vn
2223,fe16051d-d611-46b1-b19f-247f1d36a3aa,1,"Xác nhận OPT xong đơ báo căn cước công dân đã tồn tại. Không qua bước tiếp theo, vào mail đổi mật khẩu thành công vào đăng nhập vẫn bảo sai. App chán. 1*",2021-05-27 23:11:15,3.0,3.0,vi_vn

## Newest Reviews

In [27]:
# Date parsing is local to this cell, preventing hidden dependency on another section.
app_newest = app_store_preview.assign(_parsed_date=pd.to_datetime(app_store_df["updated_at"], utc=True, errors="coerce")).sort_values("_parsed_date", ascending=False).drop(columns="_parsed_date").head(30)
google_newest = google_play_preview.assign(_parsed_date=pd.to_datetime(google_play_df["at"], utc=True, errors="coerce")).sort_values("_parsed_date", ascending=False).drop(columns="_parsed_date").head(30)
display(app_newest)
display(google_newest)

,review_id,rating,title,content,updated_at,app_version,storefront,lang
0,14548034358,1,Liên tục lỗi không thể truy cập,"Là một người dùng lâu năm của tech, ban đầu rất hài lòng về chất lượng và giao diện của app, dễ giao dịch. Nhưng vài tháng trở lại đây app lỗi rất nhiều, chỉ đăng nhập có lúc đợi cả 5p vẫn chưa đăng nhập vào trang chủ được, thứ 2 là quảng cáo nhiều, truy cập vào được tài khoản thì phải tắt 7749 ...",2026-09-14T00:44:28-07:00,6.4.6,vn,unknown
1,14520064997,1,Tần suất bị lỗi mục tài sản quá nhiều,Rất hay bị lỗi báo k có tiền k có cổ phiếu nào trong tài khoản,2026-09-06T21:11:54-07:00,6.4.6,vn,unknown
2,14520054584,2,Khá tệ,"App rất lag, đôi khi còn không vào được",2026-09-06T21:07:12-07:00,6.4.6,vn,unknown
3,14504211053,3,Quá chậm,"Áp giao dịch gì mà chậm như rùa,mong bqt cải tiến",2026-09-02T20:32:43-07:00,6.4.6,vn,unknown
4,14468902446,1,Nghi vấn bán dữ liệu cho lái,"Tôi cầm cổ phiếu DBC 4 tháng, ngay khoảnh khắc khớp lệnh mua, cổ phiếu không một lần giá xanh, liên tiếp giảm 4 tháng liền. Tôi chấp nhận nạp tiền giữ vị thế margin, tuy nhiên sau 4 tháng, tôi muốn đổi cổ phiếu để có vị thế khác, ngay khoảnh khắc bán thì cổ phiếu DBC khớp lệnh và bay liên tiếp. ...",2026-08-24T21:00:51-07:00,6.4.4,vn,unknown
5,14467591535,5,NGUYEN VAN PHUONG,Namkuto,2026-08-24T12:29:06-07:00,6.4.4,vn,unknown
6,14465859621,1,"Giao diện rối khó sử dụng, CSKH kém, không thể gọi được NV CSKH","- UI UX kém, dễ bị bấm nhầm mua và bán\n- hotline chỉ để làm cảnh, AI trả lời tự động không giải quyết được vấn đề\n- không gọi được nv cskh, email không trả lời",2026-08-24T03:08:22-07:00,6.4.4,vn,unknown
7,14465018475,1,App lỗi quá nhiều,Nói chung quá tệ,2026-08-23T20:57:52-07:00,6.4.4,vn,unknown
8,14445501649,1,UI UX lởm quá,"UI UX này hoàn toàn ko phù hợp với iPad, chắc dev lười nên bê nguyên web sang. App chạy rất bất tiện, thao tác hoàn toàn lệch, ko hề chính xác. Dùng app thế này mà giao dịch thì lỗ nặng.",2026-08-18T22:09:21-07:00,6.4.4,vn,unknown
9,14439296592,1,Cách xác thực sự quá ngu,Lần đầu tiên tôi thấy việc xác thực để mở connection nhận data từ websocket nó ngớ ngẩn như vậy. Cứ 24 tiếng lại phải chạy vô app lấy cái OTP bằng tay xong đi cập nhật biến môi trường trước giờ giao dịch để k bị miss data. Đều đặn hằng ngày. Dev bên này nên thử mở cái docs của DNSE với SSi họ là...,2026-08-17T08:52:20-07:00,6.4.4,vn,unknown
10,14425846977,1,"Làm ăn ko kỹ càng, cẩu thả","Các công ty đã rời sàn như HLG thì bị tcinvest loại luôn khỏi list, làm nhà đầu tư mất luôn thông tin số lượng cổ phiếu đang sở hữu. Ko thể nào biết để gặp cty HLG làm giấy xác nhận. Nhiều mã rời sàn như hiện nay thì mất rất nhiều. List tôi gồm 100 loại cổ phiếu nên ko nhớ được",2026-08-14T01:14:42-07:00,6.4.4,vn,unknown
11,14420925724,2,Giao diện kém,"Nhiều tính năng mà đặt lệnh cổ phiếu rối quá, cần xem danh mục thì phải bấm tab khác",2026-08-12T19:12:57-07:00,6.4.4,vn,unknown
12,14418152911,1,Quá phiền hà,"Phục vụ quá cứng nhắc thay số điện thoại, cccd bắt yêu cầu mở thẻ ngân hàng để xác minh thông tin.",2026-08-12T03:46:04-07:00,6.4.4,vn,unknown
13,14414751396,1,App như cặc,App như lol mỗi vào để điền thông tin xác thực thôi mà đen xì ko hiện ra 1 cái gì . Ngân hàng lớn mà thuê team IT trình độ kém quá,2026-08-11T07:10:45-07:00,6.4.4,vn,unknown
14,14409630266,1,"Tại sao lại giam tiền 2 hợp đồng, trong khi đã đóng vị thế trong cùng 1 ngày","10/08/2026 Tại sao lại giam tiền 2 hợp đồng, trong khi đã đóng vị thế trong cùng 1 ngày, các ngày khác không giam vẫn rút được bình thường chỉ trừ thuế phí, và vị thế đóng bị lỗ, rất thất vọng về TCBS",2026-08-10T00:58:38-07:00,6.4.4,vn,unknown
15,14381104681,1,"Ko rút tiền được, bị giam tiền","Ko đăng nhập được để rút tiền, lúc cần thì ko rút tiền được phải đi vay tiền nóng.",2026-08-02T20:15:17-07:00,6.4.4,vn,unknown
16,14354074084,1,Bảo mật ngou như con bò,Dcmm xoá đi tải lại thì bắt xác nhận đăng nhập iotp trên máy đã đăng kí trc đó trong khi dùng đúng máy đó nhưng lại k cho đăng nhập vào dcm code ngoulol,2026-07-27T05:11:15-07:00,6.4.4,vn,unknown
17,14352635121,1,App lỗi rất nhiều lần,"App hay bị lỗi quay vòng vòng chờ dữ liệu, rồi lâu lâu đặt lệnh thì không được rất bực mình, tỷ lệ lỗi rất nhiều",2026-07-26T19:35:18-07:00,6.4.4,vn,unknown
18,14352633073,1,Không có nhân viên hỗ trợ,Dịch vụ kém,2026-07-26T19:34:31-07:00,6.4.4,vn,unknown
19,14341132155,5,Dùng thích,"Tuy giao diện không đẹp nhưng rất tuyệt vời rồi, đầu tiên thì phí giao dịch ổn không quá đắt, lại thêm cái widget nữa tiện quá muốn xem giá không cần vào app",2026-07-23T21:57:36-07:00,6.4.4,vn,unknown
20,14313162800,1,Giam Tiền cổ tức,App này chuyên giam Tiền cổ tức đợi cuối ngày hết giao dịch mới nhả Tiền ra trong khi công ty chứng khoán khác Tiền đã về để cho giao dịch trong phiên.,2026-07-16T23:45:43-07:00,6.4.4,vn,unknown
21,14296658625,1,App rất thường bị lỗi,Rất thường gặp lỗi đăng nhập,2026-07-12T21:19:17-07:00,6.4.4,vn,unknown
22,14280577109,3,Ok,"có một số bitcoin nhưng app hk có tính năng nạp trực tiếp , mong là sẽ có thêm tính năng này sớm",2026-07-08T21:08:14-07:00,6.4.4,vn,unknown
23,14223394760,1,App tệ,"App rắc rối. Rất khó dùng. Nhiều mục không cần thiết cho nđt mà cũng chưng hết ra, rối rắm.\nCực kỳ khó dùng so với các app chứng khoán khác như của Ssi, vnd, vps.\nTôi đã dùng nhiều app khác rồi mà dùng app Tcbs này thực sự rất bực mình luôn.",2026-06-24T22:43:41-07:00,6.4.4,vn,unknown
24,14162695649,2,Số liệu sai,"App tài chính mà số liệu không chuẩn gì hết. Sáng nạp 10tr, chưa mua bán gì mà tối vào không thấy tiền đâu nữa. F5 thì thấy nháy 10tr rồi biến mất. \n\nĐến tổng số vốn cũng nhảy loạn lên, không track được lỗ lãi gì hết.",2026-06-09T08:53:51-07:00,6.4.4,vn,unknown
25,14149839961,1,Cái ipower lúc ẩn lúc hiện như ma,Lúc cần rút tiền thì tính năng ipower bị biến mất không rút tiền được,2026-06-06T01:12:27-07:00,6.4.4,vn,unknown
26,14147186413,1,Ứng dụng hệ thống như một tên bịp bợm.,Chức năng “ứng tiền trước” giờ có giới hạn dù mình không dùng chức năng này đã lâu.\nVà nợ phí lưu ký thì không tự động trừ tiền dù có liên kết tài khoản hay đã nạp tiền. Nợ đó cứ bị tính lãi cao lên như ăn cướp vậy. Dịch vụ chỉ muốn cướp đoạt tài sản của người khác. Không nên dùng.,2026-06-05T08:28:37-07:00,6.4.4,vn,unknown
27,14142865973,1,Ai như tôi không nạo tiền vào không lâu tiền bay hết sạch,Chắn,2026-06-04T06:07:36-07:00,6.4.4,vn,unknown
28,14141897416,5,Good,"App tốt, cskh tuyệt vời và kịp thời",2026-06-03T23:40:04-07:00,6.4.4,vn,unknown
29,14051715882,1,Quá tệ cho 1 sàn do ngân hàng đầu ngành vận hành,Tiền phong tỏa khi hủy lệnh rất chậm trong khi lệnh hủy từ 3 4 tiếng trước. Quá tệ cho 1 sàn chứng khoán được vận hành bởi ngân hàng lớn.,2026-05-11T00:18:29-07:00,6.4.3,vn,unknown

,reviewId,score,content,at,reviewCreatedVersion,appVersion,collection_locale
0,6638c299-2864-4386-837e-41064b75be48,1,sao cứ cứng đơ không nhích nhút gõ bất kỳ một chữ nào được....,2026-09-21 12:13:27,NaN,NaN,vi_vn
1,45b7bb0f-cd74-43a9-9b85-bd050b6a1f9f,1,Mới dùng thử . App giao diên quá chán. Dùng tcbs . Mà phải vào ssi xem giá . .ap quá chán luôn .,2026-09-21 05:51:18,6.4.5,6.4.5,vi_vn
2,4ae66065-e785-4516-a20d-51040c7a80d2,1,"rẻ rách, đã rườm rà còn khó xài",2026-09-18 18:49:22,6.4.5,6.4.5,vi_vn
3,f93f9a8e-c094-4ceb-8268-f4ba73dbb18c,1,"bắt làm chữ ký số mà cứ chụp ảnh xong là đơ, ko làm đc cái gì nữa, xóa đi cài lại vẫn thế",2026-09-15 22:04:51,6.4.5,6.4.5,vi_vn
4,ef9573f5-cac7-4b27-857a-f29bebf2c4d2,3,"Tôi đang sở hữu quỹ tcef đặt mua thêm ccq ngay trong tcef mà khi đặt lệnh lại lòi ra lệnh mua tcbf là sao vậy, ai code app kỳ vậy",2026-09-14 08:56:29,6.4.5,6.4.5,vi_vn
5,b60631dc-52f7-4a6e-ab62-777981d617ec,1,"Giao diện app quá tệ. Tính năng cơ bản như xem chart và đặt lệnh chuyển qua lại rất phức tạp, tôi muốn vừa xem chart nhanh vừa đặt lệnh nhiều ngày (24/7) đơn giản, mà app quá rườm rà, giao diện nhiều tính năng rác không dùng đến chiếm hết chỗ. Muốn xem danh mục của tôi đang giữ biến động thế nào...",2026-09-11 15:57:15,6.4.5,6.4.5,vi_vn
6,7d25eb7f-ac40-4de4-8943-5ab02a03cdbf,1,"App Techcombank Mobile nhanh bao nhiêu thì app TCBS chậm bấy nhiêu, đó là vì TCB mobile có giao diện đơn giản. Để cải thiện, các bạn cần đơn giản hóa giao diện, các cửa sổ lựa chọn chỉ nên hiện những gì cần thiết, cơ bản (các tính năng thông minh khác dành cho nhà đầu tư chuyên nghiệp nên được c...",2026-09-09 06:36:39,NaN,NaN,vi_vn
7,84a4e782-1615-4764-ad24-3974c5da8eb0,2,app lag giật khó dùng,2026-09-08 08:36:53,6.4.5,6.4.5,vi_vn
2712,7fd64ff8-fbd4-4520-a656-c439f9e4443d,1,"Đội ngũ hỗ trợ xử lý chậm chạp, lề mề. Tài khoản khách hàng cần mở khóa, phải chạy lên chi nhánh TCB kí giấy. Rùi phải đợi 2-3 ngày vận chuyển giấy tờ từ TCB ra TCBS chi nhánh HN. Sau đó phải đợi xử lý tờ giấy, rùi đợi 24 giờ để mở khóa. Loằng ngoằng như thời cổ đại.",2026-09-05 11:12:28,NaN,NaN,en_vn
8,74c2b3de-07a9-4e83-afe4-76ce8134f8f0,1,"Rất tệ yêu cầu mã iOTP mà chờ gần 30p không có , liên hệ nhân viên thì không được , hệ thống quản lý quá kém",2026-08-29 21:30:32,6.4.5,6.4.5,vi_vn
9,5bac4bc7-ad1e-45fe-858c-84c7185e971a,1,"Ứng dụng lỏi, vô tạo tài khoản bấm tiếp tục mãi k đc",2026-08-28 23:10:48,6.4.14,6.4.14,vi_vn
10,9450f8ac-d9ba-4f47-b7f2-3271066a7707,1,app lỗi vcl. không quay vid xác thực khuôn mặt được. quá tệ,2026-08-25 10:25:19,6.4.5,6.4.5,vi_vn
11,9e1764d8-c3f8-42aa-ae90-cd5c55046620,2,"Phần đặt lệnh, hiển thị các mức giá chờ khớp chưa được dễ dùng như của FPT và SSI",2026-08-24 16:45:37,NaN,NaN,vi_vn
12,036f8109-831e-469c-bbe2-1b284129e69b,5,Tôi thấy dùng tốt bình mà sao mọi người bình luận tệ thế nhỉ hay do mới tham gia thị trường nên vậy,2026-08-21 17:39:02,6.4.5,6.4.5,vi_vn
2713,ef99efd2-9f92-42ab-8b4c-3c4e41370ef3,1,"Very bad exp. It required users to input a certain message in each transfer (your full name and account in TCBS (aka Techcombank Securities, this app). Even if you transfer money from your Techcombank app, but forgot to input that abovementioned info, your money goes to vague. It doesn't return ...",2026-08-18 15:10:00,6.4.5,6.4.5,en_vn
13,b80c2d64-7ce6-4036-9237-860697ee5178,1,"chậm, lag quá ạ",2026-08-12 15:23:48,6.4.5,6.4.5,vi_vn
14,70b1c57f-f62a-4b30-b5cb-08fef6063ccd,2,"App làm rối quá, làm như SSI hay MBS cho dễ sử dụng.",2026-08-10 15:03:03,6.4.5,6.4.5,vi_vn
15,01ad6ded-2aab-45a5-b0c7-e94d5828b921,1,lag,2026-08-07 09:24:22,6.4.1,6.4.1,vi_vn
16,e5ec7f53-687e-43a7-aa2c-55e6ead04049,1,"App quá chán. Lúc cần bán thì k vào dc, dựt lag quá",2026-08-04 20:07:41,6.4.5,6.4.5,vi_vn
17,5d89ab13-4007-48a8-8e02-6279e531d636,5,"tạm thời Ok. +Phần đăng ký: đăng ký online hôm trước thì hôm sau được duyệt để mua rồi. + Phí giao dịch : khi mua là phí 0.03% khá rẻ, khi bán là phí 0.03% và thuế TNCN 0.1% + Sau khi chuyển tiền thì tầm 1 phút mới cập nhật số dư. + Sau khi bán là phần tiền bán 2 ngày sau mới về tài khoản để rút...",2026-08-01 17:01:26,6.4.5,6.4.5,vi_vn
18,02cf4533-f984-4fee-9f9a-dfcca55f1a06,1,Tạo tài khoản không cho tạo r hiện sđt không hợp lệ?? Vậy tạo app chi mà không cho người dùng giao dịch??,2026-07-29 21:49:39,6.4.5,6.4.5,vi_vn
2714,d372596f-4533-497c-9bb3-f0c9a37ae542,2,"Tcbs đang bị lỗi, k vào dc bảng giá và hiển thị sai màu trong mục tài sản, bị từ đầu tuần rồi mà sắp cuối tuần rồi cũng chưa fix xong",2026-07-29 11:14:05,6.4.5,6.4.5,en_vn
19,ab2dfff3-3256-4426-bcff-90608588dd94,2,"không khớp được lệnh mặc dù lệnh LO , giá mua cao hơn giá rao bán vẫn không khớp",2026-07-25 16:01:59,6.4.5,6.4.5,vi_vn
20,07616126-4fd6-4860-a991-a0a6ea51f192,5,mong đợi,2026-07-24 10:33:14,6.4.5,6.4.5,vi_vn
21,56f40fd1-9968-4020-a53d-7faa5f81b4ba,5,good,2026-07-16 08:30:18,5.8.13,5.8.13,vi_vn
22,e7a9cf27-0878-42f7-8972-3a2542c2af3f,1,"phần mềm tồi tệ, xác minh khuôn mặt cả nghìn lần không được.",2026-07-15 08:11:02,NaN,NaN,vi_vn
2715,ecc8fa90-86b6-40a9-9c90-a7385d972c5b,4,"bảng giá mất tính năng tự xoay ngược khi chuyển sang dạng ngang, bất tiện khi cắm sạc, vì phải vòng dây, phiên bản trước thì được, kiểm tra lại nha, đa tạ",2026-07-13 11:06:20,6.4.5,6.4.5,en_vn
23,1eb01879-8d2e-41ce-a4b4-1dfd9c6ffd53,1,"App lag, lỗi lurg tung, liên kết TCB gì mãi chả được, số dư thì hiện chập chờn Bó tay",2026-07-11 12:10:10,6.4.5,6.4.5,vi_vn
24,8a6e6c41-9bfb-4a15-bbae-c2f83ead1bda,1,"phí rẻ nên xài. nhưng quản lý lời lỗ phải nhờ excel, xem bảng giá phải nhờ SSI. nói chung được mỗi cái phí rẻ. app lởm quá.",2026-07-09 14:51:45,NaN,NaN,vi_vn
25,0965c4ed-df13-48d6-b0f0-8f5c739800da,1,"không xác nhận được sinh trắc học, lúc nộp video nó load gần 1h không xong phần submitting the vertification, không đăng ký được",2026-07-09 11:24:32,6.4.5,6.4.5,vi_vn

## Oldest Reviews

In [28]:
# Date parsing is local to this cell, preventing hidden dependency on another section.
app_oldest = app_store_preview.assign(_parsed_date=pd.to_datetime(app_store_df["updated_at"], utc=True, errors="coerce")).sort_values("_parsed_date").drop(columns="_parsed_date").head(30)
google_oldest = google_play_preview.assign(_parsed_date=pd.to_datetime(google_play_df["at"], utc=True, errors="coerce")).sort_values("_parsed_date").drop(columns="_parsed_date").head(30)
display(app_oldest)
display(google_oldest)

,review_id,rating,title,content,updated_at,app_version,storefront,lang
521,9819441432,3,Hay bị lỗi app,Cứ vài ngày là lỗi app phãi xoá đi tải lại hoài.,2023-04-13T20:22:33-07:00,5.0.1,vn,unknown
520,10191157286,4,Máy bị xoay ngang ko xoay lại đc,"macbook pro m1 app bị lỗi, bị xoay ngang ko xoay lại đc",2023-07-28T03:58:35-07:00,5.0.1,vn,unknown
519,10217332140,3,Nâng cấp phải giữ bản cũ,"Nâng cấp phải giữ bản cũ, tôi dùng ios 12.5.7 không vào được! Giờ phải thay điện thoại! Các app bên Cty Ck khác đều dùng được",2023-08-03T20:54:21-07:00,5.1,vn,unknown
518,10383443236,5,TCBS,"App rất tuyệt vời, mọi giao dịch đều nhanh chóng chính xác, đánh giá trên cả 5 sao!\nTài khoản TCBS: 105CA07444",2023-09-18T22:03:19-07:00,5.1,vn,unknown
517,11124085882,3,không đổi được mật khẩu,"tạo tài khoản xong, vào ứng dụng bắt đổi mật khẩu mãi mà hok đổi được. admin kiểm tra lại giùm mình với",2024-04-05T05:18:45-07:00,5.5,vn,unknown
516,11708342893,1,Tệ,Dịch vụ cskh trực tuyến tệ! Xử lý vấn đề trên app tệ! Lỗi app tệ,2024-09-10T00:01:09-07:00,5.7,vn,unknown
515,11736875655,5,Hữu ích,Giao dịch tiện lợi và nhanh chóng,2024-09-18T03:02:07-07:00,5.7,vn,unknown
514,11736877477,5,Rất là ok,Nhanh gọn thuận tiện,2024-09-18T03:02:55-07:00,5.7,vn,unknown
513,11736879163,5,App rất dễ sử dụng,Nhiều tiện ích Stk 105CH91198,2024-09-18T03:03:40-07:00,5.7,vn,unknown
512,11736881714,5,105CP01787,105CP01787 tôi thích bảng giá,2024-09-18T03:04:46-07:00,5.7,vn,unknown
511,11736881923,5,Tài khoản: 105CB49266,Tài khoản: 105CB49266\nÁp rất tiện lợi. Giao dịch mua bán cổ phiếu thuận tiện và dễ sử dụng,2024-09-18T03:04:51-07:00,5.7,vn,unknown
510,11736882017,5,Tuyệt vời,105CBLBD05 tôi yêu thích bảng giá,2024-09-18T03:04:53-07:00,5.7,vn,unknown
509,11736882418,5,Ứng dụng dễ sử dụng,Ứng dụng với giao diện và thao tác dễ thực hiện,2024-09-18T03:05:03-07:00,5.7,vn,unknown
508,11736883334,5,Oke,Ứng dụng tiện ích giúp chúng tôi kiểm soát đc tk bảo mật,2024-09-18T03:05:27-07:00,5.7,vn,unknown
507,11736883500,5,Techcombank,"Ứng dụng dễ xài, nhiều tiện ích",2024-09-18T03:05:31-07:00,5.7,vn,unknown
506,11736886805,5,105CF89579,105CF89579 tôi thích bảng giá,2024-09-18T03:06:56-07:00,5.7,vn,unknown
505,11736887227,5,Đánh giá ứng dụng.,105CHUUTAI tôi thích bảng giá,2024-09-18T03:07:07-07:00,5.7,vn,unknown
504,11736887458,5,105CNL6686,105CNL6686 good,2024-09-18T03:07:14-07:00,5.7,vn,unknown
503,11736888952,5,105CHNQ688,"105CHNQ688\nBảng giá mượt mà, nhiều công cụ hữu ích để phục vụ nhu cầu của nhà đầu tư.",2024-09-18T03:07:55-07:00,5.7,vn,unknown
502,11736889608,5,105CTOIYEUVN,Chất lượng dịch vụ quá tốt,2024-09-18T03:08:12-07:00,5.7,vn,unknown
501,11736890063,5,good,xài tốt nhưng lãi margin hơi cao,2024-09-18T03:08:24-07:00,5.7,vn,unknown
500,11736890736,5,App Techcombank,"Qua 5 năm sử dụng , App Techcombank ổn định, dễ dàng sử dụng và có tính bảo mật cao",2024-09-18T03:08:40-07:00,5.7,vn,unknown
499,11736891062,5,105CTOIYEUVN tôi thích bảng giá,Good,2024-09-18T03:08:49-07:00,5.7,vn,unknown
498,11736891535,5,Tuyệt,105CT10298 quá ok,2024-09-18T03:09:02-07:00,5.7,vn,unknown
497,11736894984,5,Đánh giá,"Ứng dụng ok, dùng mượt",2024-09-18T03:10:31-07:00,5.7,vn,unknown
496,11736896147,5,105CANHVU5 tôi yêu TCBS,Tuyệt zời,2024-09-18T03:11:01-07:00,5.7,vn,unknown
495,11736898699,5,Good,105CG56299 tôi thích tcbs,2024-09-18T03:12:05-07:00,5.7,vn,unknown
494,11736900062,5,Ngon,Ngon,2024-09-18T03:12:42-07:00,5.7,vn,unknown
493,11736902250,5,105CLK3999,105clk3999 tôi thích bảng giá,2024-09-18T03:13:40-07:00,5.7,vn,unknown
492,11736905097,5,Tốt,"Ap rõ ràng, dễ giao dịch\n\n105CYV2909",2024-09-18T03:14:55-07:00,5.7,vn,unknown

,reviewId,score,content,at,reviewCreatedVersion,appVersion,collection_locale
3222,d9cf435b-e857-4894-9aaf-363abf995b71,5,Very convenience to trade on Vietnam stock market,2015-08-13 11:10:30,1.0,1.0,en_vn
3221,971758e7-1b59-445f-941f-e44c69810165,5,Clean and Fast. Menu needs to improve for more convenient.,2015-08-24 15:06:49,NaN,NaN,en_vn
2711,0f1413df-783e-42a6-8532-e1654d507521,5,Ok,2015-09-02 11:07:10,1.0,1.0,vi_vn
3220,e8718449-090f-4cbd-8471-9b767f2065fc,1,Phần mềm không cài đc trên note 4 :(,2015-09-13 19:32:39,NaN,NaN,en_vn
2710,d916d16d-74cd-41ca-86ca-fb57447b18da,4,Phần mềm cập nhật thông tin chậm. Đăng nhập đôi lúc k vào được. Tài khoản tổng tính hay bị sai khi giá cổ phiếu tăng lên hay giảm xuống. Phần trăm lãi bị nhầm lẫn khi chuyển cổ phiếu qua lại giữa thường và ký quỹ. Nhìn chung ứng dụng này chưa tốt cả về sự mượt mà lẫn cập nhật thông tin thị trường.,2016-08-14 08:24:52,1.1,1.1,vi_vn
2709,18ab7cb9-5b97-4365-a57e-882af1ce245a,4,"Thông tin cập nhật hay bị sai, giá cp lên xuống ko được cập nhật đúng. Không cho bán lô lẻ như FPTS. Hy vọng TCBs sớm fix lỗi.",2016-09-19 11:33:26,1.1,1.1,vi_vn
3219,0de9b206-e6bf-4af4-9c22-b5c7384f77b3,1,Vừa đăng nhập xong 2' thì tự quit,2016-10-25 14:46:57,1.1.1,1.1.1,en_vn
2708,9bbd9691-fab8-4b68-9aad-24f1f40c0742,2,Cập nhật chậm. Tính sai tổng tài sản. Đề nghị cập nhật,2017-07-12 13:02:47,1.1.2,1.1.2,vi_vn
2707,f98616ef-454c-4196-a4fb-65d9ffc1ae97,2,"1. Bảng giá hiển thị bị làm tròn số. Vd: giá 39.15 làm tròn thành 39.2 2. Danh mục đầu tư chưa tính lãi/lỗ tổng cộng 3. Không có thông tin về cổ phiếu ( biểu đồ giá + klg, báo cáo tài chính: tổng quan + chỉ tiêu + chỉ số, tin tức thị trường liên quan,...) 4....",2017-10-09 11:09:47,1.1.6,1.1.6,vi_vn
3218,27976d92-a850-4c7f-bc10-aa36403ade07,1,"Cài đặt xong nhưng không thể đăng nhập sử dụng, liên tục báo lỗi connection failed, mặc dù đăng nhập bằng account & code đang sử dụng trên bản web.",2017-12-02 10:39:36,1.1.6,1.1.6,en_vn
2706,1d5a95f5-3633-4553-b1de-dd37e47a0a0e,1,Ứng dụng quá kém,2018-01-18 19:45:53,1.1.6,1.1.6,vi_vn
3217,6e6e2256-a5b9-47e5-9904-1c16de158086,1,Đăng nhâp liên tục báo Đang đăng nhập ở nơi khác. Phải nhập rất nhiều lần mới vào đc. Dữ liệu chi tiết giá hiển thị liên tục bị mất. Cái app k thể tệ hơn. Quá thất vọng,2018-03-30 11:20:25,1.1.6,1.1.6,en_vn
2705,cea24230-a9da-4378-9975-5f5b7861f81f,2,Lỗi trên android,2018-05-09 13:25:53,NaN,NaN,vi_vn
2704,28826774-b7fb-426e-924c-e89362e11099,3,Khi nhập mã CK phân biệt chữ hoa chữ thường - ko tiện,2018-05-10 10:04:26,1.1.6,1.1.6,vi_vn
3216,3fb54262-50d3-40da-8c76-ce93774a02e0,1,Ứng dụng bị lỗi hoàn toàn mong ad fix sớm,2018-05-18 08:37:35,1.1.6,1.1.6,en_vn
2703,2f36cd1c-0aed-416c-97a0-0e6050b14dab,4,Tạm ổn,2018-07-05 23:43:57,1.1.6,1.1.6,vi_vn
2702,82b65da1-0d60-4fc5-8c36-02ea47bbfc72,1,Không đăng nhập được.,2018-07-11 04:59:53,NaN,NaN,vi_vn
2701,ba501936-f6b7-4acf-a53b-019b2f5a3939,1,Ứng dụng chất lượng quá kém,2018-07-20 14:19:33,1.1.6,1.1.6,vi_vn
2700,cfb8b137-90bf-4efd-900e-c2d59f954bcc,3,Ứng dụng hay bị lag ra. Hi vọng TCB fix sớm,2018-08-03 07:24:10,1.1.7,1.1.7,vi_vn
2699,10af4e10-4652-4c23-9faf-139e64150383,1,Quá tệ. Thiết lập chán chê rồi vẫn chưa có thông tin tài khoản đăng nhập.,2018-08-20 09:07:36,1.1.7,1.1.7,vi_vn
3215,0a0bf54d-f5bc-400b-ac9d-b848b775c877,1,Không đăng nhập được?,2018-08-29 01:21:15,1.1.7,1.1.7,en_vn
2698,c2415b6c-fe69-4e84-a7bf-78ca7f9cf5ec,5,Rât tốt,2018-09-21 19:36:06,1.1.7,1.1.7,vi_vn
2697,7b01bcf9-a5d6-44ac-b44a-5a8b742d8064,1,Ko xai dc,2018-10-18 09:50:48,1.1.7,1.1.7,vi_vn
3214,db4533f9-2f7b-4bcf-ad19-99a55f60e9e8,1,"Sập liên tục, thông tin nghèo nàn",2018-10-30 18:23:02,1.1.7,1.1.7,en_vn
2696,2e163ef8-f409-449b-9980-56f16d2aca86,4,ok,2019-02-14 23:19:46,1.1.7,1.1.7,vi_vn
2695,e87ca58b-7d1a-4b01-91d4-7aa14aae3d2e,1,quá tệ,2019-03-14 16:43:41,NaN,NaN,vi_vn
2694,2d85965e-0e48-4ef4-8c9d-7d230b7cdb38,3,chưa ok,2019-03-17 21:24:54,1.1.7,1.1.7,vi_vn
3213,aa5ecbc2-0c4b-4b3e-8b67-1cfa3288de0a,2,một trong những app ctck tệ nhất mà tôi từng sử dụng. Giao diện khó hiểu lỗi liên tục.,2019-04-03 09:29:56,1.1.7,1.1.7,en_vn
3212,ef1b3f84-43b4-4434-9d0d-d150d6b6e201,1,"Dở tệ, cực khó khi đặt mua CP vì hiển thị đồng thời bàn phím ảo, dẫn đến việc gõ bằng bàn phím mặc định sẽ bị báo lỗi. ko câph nhật thay đổi số tiền khi cổ phiếu thay đổi",2019-04-18 11:15:21,1.1.7,1.1.7,en_vn
2693,e88c73e2-9e48-4553-9c0b-b46833458594,1,ứng dụng kém,2019-06-05 14:44:21,NaN,NaN,vi_vn

## App Store Inspection

In [29]:
APP_STORE_INSPECTION_RATING = 1  # Change to 1, 2, 3, 4, or 5.
app_inspection = app_store_preview.assign(_parsed_date=pd.to_datetime(app_store_df["updated_at"], utc=True, errors="coerce"))
app_checks = pd.Series({
    "rows": len(app_store_df),
    "unique_review_id": app_store_df["review_id"].nunique(),
    "duplicate_review_id_records": int(app_store_df["review_id"].duplicated(keep=False).sum()),
    "missing_content": int(app_store_df["content"].isna().sum()),
    "missing_rating": int(app_store_df["rating"].isna().sum()),
    "missing_updated_at": int(app_store_df["updated_at"].isna().sum()),
})
display(app_checks.rename("count").to_frame())
print("Random 20")
display(app_store_preview.sample(n=20, random_state=42))
print("Earliest 20")
display(app_inspection.sort_values("_parsed_date").drop(columns="_parsed_date").head(20))
print("Latest 20")
display(app_inspection.sort_values("_parsed_date", ascending=False).drop(columns="_parsed_date").head(20))
print(f"Rating {APP_STORE_INSPECTION_RATING}: up to 20")
display(app_store_preview[pd.to_numeric(app_store_preview["rating"], errors="coerce").eq(APP_STORE_INSPECTION_RATING)].head(20))

                             count
rows                           522
unique_review_id               522
duplicate_review_id_records      0
missing_content                  0
missing_rating                   0
missing_updated_at               0

Random 20

,review_id,rating,title,content,updated_at,app_version,storefront,lang
434,11737328061,5,Tuyệt vời,105CA18669,2024-09-18T05:47:47-07:00,5.7,vn,unknown
440,11737258935,5,Dễ sử dụng,"Giao diện app dễ sử dụng, đẹp",2024-09-18T05:26:06-07:00,5.7,vn,unknown
6,14465859621,1,"Giao diện rối khó sử dụng, CSKH kém, không thể gọi được NV CSKH","- UI UX kém, dễ bị bấm nhầm mua và bán\n- hotline chỉ để làm cảnh, AI trả lời tự động không giải quyết được vấn đề\n- không gọi được nv cskh, email không trả lời",2026-08-24T03:08:22-07:00,6.4.4,vn,unknown
184,13014069107,1,lỗi chuyển tiền,k rút tiền dc,2025-08-14T01:51:40-07:00,6.0.2,vn,unknown
78,13835758727,1,TK ng thân không nộp được tiền,"Mình tạo tk con, Lần 1 nộp bằng cú pháp khi nhấn nộp tiền trên áp, 2 ngày sau trả lại báo sai cú pháp, trong khi cú pháp tự đông gen ra\n\nLần này 4 ngày rồi không back lại tiền, mà back lại cũng k biết làm thế nào để nộp",2026-03-10T21:52:51-07:00,6.4.2,vn,unknown
299,12092046546,2,Phần đặt lệnh cổ phiếu thực sự chán. Đơn điệu không hiển được thông tin thị trường thời điểm đó.,"Nhiều lúc đặt giá xong mở ra xem giá tt đã thay đổi từ lúc nào. Phần đặt khối lượng cũng vậy, nhiều lúc quên ko biết khối lượng cp của mình có bao nhiêu lại phải quay lại từ đầu để xem. Thực sự rất khó chịu",2024-12-22T01:52:10-07:00,5.8.2,vn,unknown
521,9819441432,3,Hay bị lỗi app,Cứ vài ngày là lỗi app phãi xoá đi tải lại hoài.,2023-04-13T20:22:33-07:00,5.0.1,vn,unknown
484,11736926631,5,Dich vu tot,105CH90456,2024-09-18T03:24:09-07:00,5.7,vn,unknown
117,13630948771,1,Lỗi ai chịu,"Đang lỗi không giao dịch được, hãy sử lý và có lời giải thích thoả đáng. Lỗi hơn 1 tiếng chưa có trả lời khách hàng",2026-01-13T19:07:52-07:00,6.3,vn,unknown
137,13500073382,2,Biểu đồ kỹ thuật,Biểu đồ kỹ thuật chỉ cho xem theo hình dọc hoặc quay ngang thì không được full màn xem rất khó chịu. TCBS khắc phục thêm quả này nữa thì ngon,2025-12-10T22:23:18-07:00,6.2,vn,unknown
10,14425846977,1,"Làm ăn ko kỹ càng, cẩu thả","Các công ty đã rời sàn như HLG thì bị tcinvest loại luôn khỏi list, làm nhà đầu tư mất luôn thông tin số lượng cổ phiếu đang sở hữu. Ko thể nào biết để gặp cty HLG làm giấy xác nhận. Nhiều mã rời sàn như hiện nay thì mất rất nhiều. List tôi gồm 100 loại cổ phiếu nên ko nhớ được",2026-08-14T01:14:42-07:00,6.4.4,vn,unknown
508,11736883334,5,Oke,Ứng dụng tiện ích giúp chúng tôi kiểm soát đc tk bảo mật,2024-09-18T03:05:27-07:00,5.7,vn,unknown
75,13846427918,5,ap ok mà .còn được hay không thì do kiến thức và kinh nghiệm của bản thân,lúc đầu cũng tải nhiều app coi sao sau nhưng sau 1 thời gian lấy app này ổn định dùng luôn đc 5năm rồi,2026-03-14T01:27:26-07:00,6.4.2,vn,unknown
436,11737303426,5,105CH29389 tôi thích bảng giá,105CH29389 tôi thích bảng giá,2024-09-18T05:40:06-07:00,5.7,vn,unknown
476,11736971959,5,Ứng dụng tốt,105CH68998,2024-09-18T03:42:57-07:00,5.7,vn,unknown
140,13445903889,1,"Hỗ trợ AI quá kém, không giải quyết được vấn đề",Bộ phận hỗ trợ là AI hoạt động không hiệu quả. Chỉ dẫn theo các link có sẵn nhưng vẫn không giải quyết được vấn đề.,2025-11-26T23:07:30-07:00,6.2,vn,unknown
2,14520054584,2,Khá tệ,"App rất lag, đôi khi còn không vào được",2026-09-06T21:07:12-07:00,6.4.6,vn,unknown
155,13290348242,1,Không mua bán được trên TC Invest,"Ngày 20/10/2025 thị trường có phiên giảm sâu kỷ lục hơn 94 điểm, nhưng tôi không thể mua bán cổ phiếu trên app làm danh mục của tôi lỗ nặng do không thể mua để DCA",2025-10-20T03:02:17-07:00,6.1,vn,unknown
373,11739970007,5,Đánh giá 5 sao,"105CA67716 tôi thích bảng giá, giao dịch nhanh chóng, thuận lợi, cộng đồng đoàn kết. Very good!!!",2024-09-18T23:12:33-07:00,5.7,vn,unknown
131,13572173414,1,Thái độ nhân viên,Thái độ nhân viên chăm sóc khách hàng quá tệ,2025-12-30T01:22:52-07:00,6.3,vn,unknown

Earliest 20

,review_id,rating,title,content,updated_at,app_version,storefront,lang
521,9819441432,3,Hay bị lỗi app,Cứ vài ngày là lỗi app phãi xoá đi tải lại hoài.,2023-04-13T20:22:33-07:00,5.0.1,vn,unknown
520,10191157286,4,Máy bị xoay ngang ko xoay lại đc,"macbook pro m1 app bị lỗi, bị xoay ngang ko xoay lại đc",2023-07-28T03:58:35-07:00,5.0.1,vn,unknown
519,10217332140,3,Nâng cấp phải giữ bản cũ,"Nâng cấp phải giữ bản cũ, tôi dùng ios 12.5.7 không vào được! Giờ phải thay điện thoại! Các app bên Cty Ck khác đều dùng được",2023-08-03T20:54:21-07:00,5.1,vn,unknown
518,10383443236,5,TCBS,"App rất tuyệt vời, mọi giao dịch đều nhanh chóng chính xác, đánh giá trên cả 5 sao!\nTài khoản TCBS: 105CA07444",2023-09-18T22:03:19-07:00,5.1,vn,unknown
517,11124085882,3,không đổi được mật khẩu,"tạo tài khoản xong, vào ứng dụng bắt đổi mật khẩu mãi mà hok đổi được. admin kiểm tra lại giùm mình với",2024-04-05T05:18:45-07:00,5.5,vn,unknown
516,11708342893,1,Tệ,Dịch vụ cskh trực tuyến tệ! Xử lý vấn đề trên app tệ! Lỗi app tệ,2024-09-10T00:01:09-07:00,5.7,vn,unknown
515,11736875655,5,Hữu ích,Giao dịch tiện lợi và nhanh chóng,2024-09-18T03:02:07-07:00,5.7,vn,unknown
514,11736877477,5,Rất là ok,Nhanh gọn thuận tiện,2024-09-18T03:02:55-07:00,5.7,vn,unknown
513,11736879163,5,App rất dễ sử dụng,Nhiều tiện ích Stk 105CH91198,2024-09-18T03:03:40-07:00,5.7,vn,unknown
512,11736881714,5,105CP01787,105CP01787 tôi thích bảng giá,2024-09-18T03:04:46-07:00,5.7,vn,unknown
511,11736881923,5,Tài khoản: 105CB49266,Tài khoản: 105CB49266\nÁp rất tiện lợi. Giao dịch mua bán cổ phiếu thuận tiện và dễ sử dụng,2024-09-18T03:04:51-07:00,5.7,vn,unknown
510,11736882017,5,Tuyệt vời,105CBLBD05 tôi yêu thích bảng giá,2024-09-18T03:04:53-07:00,5.7,vn,unknown
509,11736882418,5,Ứng dụng dễ sử dụng,Ứng dụng với giao diện và thao tác dễ thực hiện,2024-09-18T03:05:03-07:00,5.7,vn,unknown
508,11736883334,5,Oke,Ứng dụng tiện ích giúp chúng tôi kiểm soát đc tk bảo mật,2024-09-18T03:05:27-07:00,5.7,vn,unknown
507,11736883500,5,Techcombank,"Ứng dụng dễ xài, nhiều tiện ích",2024-09-18T03:05:31-07:00,5.7,vn,unknown
506,11736886805,5,105CF89579,105CF89579 tôi thích bảng giá,2024-09-18T03:06:56-07:00,5.7,vn,unknown
505,11736887227,5,Đánh giá ứng dụng.,105CHUUTAI tôi thích bảng giá,2024-09-18T03:07:07-07:00,5.7,vn,unknown
504,11736887458,5,105CNL6686,105CNL6686 good,2024-09-18T03:07:14-07:00,5.7,vn,unknown
503,11736888952,5,105CHNQ688,"105CHNQ688\nBảng giá mượt mà, nhiều công cụ hữu ích để phục vụ nhu cầu của nhà đầu tư.",2024-09-18T03:07:55-07:00,5.7,vn,unknown
502,11736889608,5,105CTOIYEUVN,Chất lượng dịch vụ quá tốt,2024-09-18T03:08:12-07:00,5.7,vn,unknown

Latest 20

,review_id,rating,title,content,updated_at,app_version,storefront,lang
0,14548034358,1,Liên tục lỗi không thể truy cập,"Là một người dùng lâu năm của tech, ban đầu rất hài lòng về chất lượng và giao diện của app, dễ giao dịch. Nhưng vài tháng trở lại đây app lỗi rất nhiều, chỉ đăng nhập có lúc đợi cả 5p vẫn chưa đăng nhập vào trang chủ được, thứ 2 là quảng cáo nhiều, truy cập vào được tài khoản thì phải tắt 7749 ...",2026-09-14T00:44:28-07:00,6.4.6,vn,unknown
1,14520064997,1,Tần suất bị lỗi mục tài sản quá nhiều,Rất hay bị lỗi báo k có tiền k có cổ phiếu nào trong tài khoản,2026-09-06T21:11:54-07:00,6.4.6,vn,unknown
2,14520054584,2,Khá tệ,"App rất lag, đôi khi còn không vào được",2026-09-06T21:07:12-07:00,6.4.6,vn,unknown
3,14504211053,3,Quá chậm,"Áp giao dịch gì mà chậm như rùa,mong bqt cải tiến",2026-09-02T20:32:43-07:00,6.4.6,vn,unknown
4,14468902446,1,Nghi vấn bán dữ liệu cho lái,"Tôi cầm cổ phiếu DBC 4 tháng, ngay khoảnh khắc khớp lệnh mua, cổ phiếu không một lần giá xanh, liên tiếp giảm 4 tháng liền. Tôi chấp nhận nạp tiền giữ vị thế margin, tuy nhiên sau 4 tháng, tôi muốn đổi cổ phiếu để có vị thế khác, ngay khoảnh khắc bán thì cổ phiếu DBC khớp lệnh và bay liên tiếp. ...",2026-08-24T21:00:51-07:00,6.4.4,vn,unknown
5,14467591535,5,NGUYEN VAN PHUONG,Namkuto,2026-08-24T12:29:06-07:00,6.4.4,vn,unknown
6,14465859621,1,"Giao diện rối khó sử dụng, CSKH kém, không thể gọi được NV CSKH","- UI UX kém, dễ bị bấm nhầm mua và bán\n- hotline chỉ để làm cảnh, AI trả lời tự động không giải quyết được vấn đề\n- không gọi được nv cskh, email không trả lời",2026-08-24T03:08:22-07:00,6.4.4,vn,unknown
7,14465018475,1,App lỗi quá nhiều,Nói chung quá tệ,2026-08-23T20:57:52-07:00,6.4.4,vn,unknown
8,14445501649,1,UI UX lởm quá,"UI UX này hoàn toàn ko phù hợp với iPad, chắc dev lười nên bê nguyên web sang. App chạy rất bất tiện, thao tác hoàn toàn lệch, ko hề chính xác. Dùng app thế này mà giao dịch thì lỗ nặng.",2026-08-18T22:09:21-07:00,6.4.4,vn,unknown
9,14439296592,1,Cách xác thực sự quá ngu,Lần đầu tiên tôi thấy việc xác thực để mở connection nhận data từ websocket nó ngớ ngẩn như vậy. Cứ 24 tiếng lại phải chạy vô app lấy cái OTP bằng tay xong đi cập nhật biến môi trường trước giờ giao dịch để k bị miss data. Đều đặn hằng ngày. Dev bên này nên thử mở cái docs của DNSE với SSi họ là...,2026-08-17T08:52:20-07:00,6.4.4,vn,unknown
10,14425846977,1,"Làm ăn ko kỹ càng, cẩu thả","Các công ty đã rời sàn như HLG thì bị tcinvest loại luôn khỏi list, làm nhà đầu tư mất luôn thông tin số lượng cổ phiếu đang sở hữu. Ko thể nào biết để gặp cty HLG làm giấy xác nhận. Nhiều mã rời sàn như hiện nay thì mất rất nhiều. List tôi gồm 100 loại cổ phiếu nên ko nhớ được",2026-08-14T01:14:42-07:00,6.4.4,vn,unknown
11,14420925724,2,Giao diện kém,"Nhiều tính năng mà đặt lệnh cổ phiếu rối quá, cần xem danh mục thì phải bấm tab khác",2026-08-12T19:12:57-07:00,6.4.4,vn,unknown
12,14418152911,1,Quá phiền hà,"Phục vụ quá cứng nhắc thay số điện thoại, cccd bắt yêu cầu mở thẻ ngân hàng để xác minh thông tin.",2026-08-12T03:46:04-07:00,6.4.4,vn,unknown
13,14414751396,1,App như cặc,App như lol mỗi vào để điền thông tin xác thực thôi mà đen xì ko hiện ra 1 cái gì . Ngân hàng lớn mà thuê team IT trình độ kém quá,2026-08-11T07:10:45-07:00,6.4.4,vn,unknown
14,14409630266,1,"Tại sao lại giam tiền 2 hợp đồng, trong khi đã đóng vị thế trong cùng 1 ngày","10/08/2026 Tại sao lại giam tiền 2 hợp đồng, trong khi đã đóng vị thế trong cùng 1 ngày, các ngày khác không giam vẫn rút được bình thường chỉ trừ thuế phí, và vị thế đóng bị lỗ, rất thất vọng về TCBS",2026-08-10T00:58:38-07:00,6.4.4,vn,unknown
15,14381104681,1,"Ko rút tiền được, bị giam tiền","Ko đăng nhập được để rút tiền, lúc cần thì ko rút tiền được phải đi vay tiền nóng.",2026-08-02T20:15:17-07:00,6.4.4,vn,unknown
16,14354074084,1,Bảo mật ngou như con bò,Dcmm xoá đi tải lại thì bắt xác nhận đăng nhập iotp trên máy đã đăng kí trc đó trong khi dùng đúng máy đó nhưng lại k cho đăng nhập vào dcm code ngoulol,2026-07-27T05:11:15-07:00,6.4.4,vn,unknown
17,14352635121,1,App lỗi rất nhiều lần,"App hay bị lỗi quay vòng vòng chờ dữ liệu, rồi lâu lâu đặt lệnh thì không được rất bực mình, tỷ lệ lỗi rất nhiều",2026-07-26T19:35:18-07:00,6.4.4,vn,unknown
18,14352633073,1,Không có nhân viên hỗ trợ,Dịch vụ kém,2026-07-26T19:34:31-07:00,6.4.4,vn,unknown
19,14341132155,5,Dùng thích,"Tuy giao diện không đẹp nhưng rất tuyệt vời rồi, đầu tiên thì phí giao dịch ổn không quá đắt, lại thêm cái widget nữa tiện quá muốn xem giá không cần vào app",2026-07-23T21:57:36-07:00,6.4.4,vn,unknown

Rating 1: up to 20

,review_id,rating,title,content,updated_at,app_version,storefront,lang
0,14548034358,1,Liên tục lỗi không thể truy cập,"Là một người dùng lâu năm của tech, ban đầu rất hài lòng về chất lượng và giao diện của app, dễ giao dịch. Nhưng vài tháng trở lại đây app lỗi rất nhiều, chỉ đăng nhập có lúc đợi cả 5p vẫn chưa đăng nhập vào trang chủ được, thứ 2 là quảng cáo nhiều, truy cập vào được tài khoản thì phải tắt 7749 ...",2026-09-14T00:44:28-07:00,6.4.6,vn,unknown
1,14520064997,1,Tần suất bị lỗi mục tài sản quá nhiều,Rất hay bị lỗi báo k có tiền k có cổ phiếu nào trong tài khoản,2026-09-06T21:11:54-07:00,6.4.6,vn,unknown
4,14468902446,1,Nghi vấn bán dữ liệu cho lái,"Tôi cầm cổ phiếu DBC 4 tháng, ngay khoảnh khắc khớp lệnh mua, cổ phiếu không một lần giá xanh, liên tiếp giảm 4 tháng liền. Tôi chấp nhận nạp tiền giữ vị thế margin, tuy nhiên sau 4 tháng, tôi muốn đổi cổ phiếu để có vị thế khác, ngay khoảnh khắc bán thì cổ phiếu DBC khớp lệnh và bay liên tiếp. ...",2026-08-24T21:00:51-07:00,6.4.4,vn,unknown
6,14465859621,1,"Giao diện rối khó sử dụng, CSKH kém, không thể gọi được NV CSKH","- UI UX kém, dễ bị bấm nhầm mua và bán\n- hotline chỉ để làm cảnh, AI trả lời tự động không giải quyết được vấn đề\n- không gọi được nv cskh, email không trả lời",2026-08-24T03:08:22-07:00,6.4.4,vn,unknown
7,14465018475,1,App lỗi quá nhiều,Nói chung quá tệ,2026-08-23T20:57:52-07:00,6.4.4,vn,unknown
8,14445501649,1,UI UX lởm quá,"UI UX này hoàn toàn ko phù hợp với iPad, chắc dev lười nên bê nguyên web sang. App chạy rất bất tiện, thao tác hoàn toàn lệch, ko hề chính xác. Dùng app thế này mà giao dịch thì lỗ nặng.",2026-08-18T22:09:21-07:00,6.4.4,vn,unknown
9,14439296592,1,Cách xác thực sự quá ngu,Lần đầu tiên tôi thấy việc xác thực để mở connection nhận data từ websocket nó ngớ ngẩn như vậy. Cứ 24 tiếng lại phải chạy vô app lấy cái OTP bằng tay xong đi cập nhật biến môi trường trước giờ giao dịch để k bị miss data. Đều đặn hằng ngày. Dev bên này nên thử mở cái docs của DNSE với SSi họ là...,2026-08-17T08:52:20-07:00,6.4.4,vn,unknown
10,14425846977,1,"Làm ăn ko kỹ càng, cẩu thả","Các công ty đã rời sàn như HLG thì bị tcinvest loại luôn khỏi list, làm nhà đầu tư mất luôn thông tin số lượng cổ phiếu đang sở hữu. Ko thể nào biết để gặp cty HLG làm giấy xác nhận. Nhiều mã rời sàn như hiện nay thì mất rất nhiều. List tôi gồm 100 loại cổ phiếu nên ko nhớ được",2026-08-14T01:14:42-07:00,6.4.4,vn,unknown
12,14418152911,1,Quá phiền hà,"Phục vụ quá cứng nhắc thay số điện thoại, cccd bắt yêu cầu mở thẻ ngân hàng để xác minh thông tin.",2026-08-12T03:46:04-07:00,6.4.4,vn,unknown
13,14414751396,1,App như cặc,App như lol mỗi vào để điền thông tin xác thực thôi mà đen xì ko hiện ra 1 cái gì . Ngân hàng lớn mà thuê team IT trình độ kém quá,2026-08-11T07:10:45-07:00,6.4.4,vn,unknown
14,14409630266,1,"Tại sao lại giam tiền 2 hợp đồng, trong khi đã đóng vị thế trong cùng 1 ngày","10/08/2026 Tại sao lại giam tiền 2 hợp đồng, trong khi đã đóng vị thế trong cùng 1 ngày, các ngày khác không giam vẫn rút được bình thường chỉ trừ thuế phí, và vị thế đóng bị lỗ, rất thất vọng về TCBS",2026-08-10T00:58:38-07:00,6.4.4,vn,unknown
15,14381104681,1,"Ko rút tiền được, bị giam tiền","Ko đăng nhập được để rút tiền, lúc cần thì ko rút tiền được phải đi vay tiền nóng.",2026-08-02T20:15:17-07:00,6.4.4,vn,unknown
16,14354074084,1,Bảo mật ngou như con bò,Dcmm xoá đi tải lại thì bắt xác nhận đăng nhập iotp trên máy đã đăng kí trc đó trong khi dùng đúng máy đó nhưng lại k cho đăng nhập vào dcm code ngoulol,2026-07-27T05:11:15-07:00,6.4.4,vn,unknown
17,14352635121,1,App lỗi rất nhiều lần,"App hay bị lỗi quay vòng vòng chờ dữ liệu, rồi lâu lâu đặt lệnh thì không được rất bực mình, tỷ lệ lỗi rất nhiều",2026-07-26T19:35:18-07:00,6.4.4,vn,unknown
18,14352633073,1,Không có nhân viên hỗ trợ,Dịch vụ kém,2026-07-26T19:34:31-07:00,6.4.4,vn,unknown
20,14313162800,1,Giam Tiền cổ tức,App này chuyên giam Tiền cổ tức đợi cuối ngày hết giao dịch mới nhả Tiền ra trong khi công ty chứng khoán khác Tiền đã về để cho giao dịch trong phiên.,2026-07-16T23:45:43-07:00,6.4.4,vn,unknown
21,14296658625,1,App rất thường bị lỗi,Rất thường gặp lỗi đăng nhập,2026-07-12T21:19:17-07:00,6.4.4,vn,unknown
23,14223394760,1,App tệ,"App rắc rối. Rất khó dùng. Nhiều mục không cần thiết cho nđt mà cũng chưng hết ra, rối rắm.\nCực kỳ khó dùng so với các app chứng khoán khác như của Ssi, vnd, vps.\nTôi đã dùng nhiều app khác rồi mà dùng app Tcbs này thực sự rất bực mình luôn.",2026-06-24T22:43:41-07:00,6.4.4,vn,unknown
25,14149839961,1,Cái ipower lúc ẩn lúc hiện như ma,Lúc cần rút tiền thì tính năng ipower bị biến mất không rút tiền được,2026-06-06T01:12:27-07:00,6.4.4,vn,unknown
26,14147186413,1,Ứng dụng hệ thống như một tên bịp bợm.,Chức năng “ứng tiền trước” giờ có giới hạn dù mình không dùng chức năng này đã lâu.\nVà nợ phí lưu ký thì không tự động trừ tiền dù có liên kết tài khoản hay đã nạp tiền. Nợ đó cứ bị tính lãi cao lên như ăn cướp vậy. Dịch vụ chỉ muốn cướp đoạt tài sản của người khác. Không nên dùng.,2026-06-05T08:28:37-07:00,6.4.4,vn,unknown

## Google Play Inspection

In [30]:
google_inspection = google_play_preview.assign(_parsed_date=pd.to_datetime(google_play_df["at"], utc=True, errors="coerce"))
google_checks = pd.Series({
    "rows": len(google_play_df),
    "unique_reviewId": google_play_df["reviewId"].nunique(),
    "duplicate_reviewId_records": int(google_play_df["reviewId"].duplicated(keep=False).sum()),
    "missing_content": int(google_play_df["content"].isna().sum()),
    "missing_score": int(google_play_df["score"].isna().sum()),
    "missing_at": int(google_play_df["at"].isna().sum()),
    "missing_reviewCreatedVersion": int(google_play_df["reviewCreatedVersion"].isna().sum()),
    "missing_appVersion": int(google_play_df["appVersion"].isna().sum()),
})
display(google_checks.rename("count").to_frame())
assert google_checks["missing_appVersion"] == 459
print("Collection locale counts")
display(google_play_df["collection_locale"].value_counts(dropna=False).rename("count").to_frame())
print("Random 20")
display(google_play_preview.sample(n=20, random_state=42))
print("Earliest 20")
display(google_inspection.sort_values("_parsed_date").drop(columns="_parsed_date").head(20))
print("Latest 20")
display(google_inspection.sort_values("_parsed_date", ascending=False).drop(columns="_parsed_date").head(20))

                              count
rows                           3223
unique_reviewId                3223
duplicate_reviewId_records        0
missing_content                   0
missing_score                     0
missing_at                        0
missing_reviewCreatedVersion    459
missing_appVersion              459

Collection locale counts

                   count
collection_locale
vi_vn               2712
en_vn                511

Random 20

,reviewId,score,content,at,reviewCreatedVersion,appVersion,collection_locale
299,abff860a-3329-408e-a188-cf64dac8a665,1,"Ứng dụng rối nuồi khó sử dụng, lag, lỗi",2025-01-01 16:09:11,5.8.11,5.8.11,vi_vn
501,5db4f5b8-b014-46c1-ade1-9220e003ca81,1,Rối rắm. Khó dùng. Lag. Chậm. Nếu có 0 sao thì 1 sao cũng k xứng đáng,2024-08-02 09:27:56,NaN,NaN,vi_vn
631,08de7a4a-fecb-4600-a727-064057aee775,5,105C0910TA tôi thích bảng giá,2024-03-04 21:45:44,5.4.1,5.4.1,vi_vn
2098,9229dec5-3fce-4985-b83a-8b5da1fb7817,2,Lúc nào cũng gặp trục trặc với iOTP,2021-08-25 23:26:43,3.1.1,3.1.1,vi_vn
1377,b840a5c7-9bbb-4e6f-badd-e6c1fd2f5d4a,1,Cài hoài ko được,2022-04-26 19:56:17,NaN,NaN,vi_vn
1709,cc027484-9281-42c5-a44f-5bb297451ded,1,Ức chế những lúc thị trường điều chỉnh mạnh. Thích là không cho đặt lệnh. Buồn buồn là chơi lớn cấm cửa không cho giao dịch. Quá tệ.,2021-11-23 11:41:12,3.1.1,3.1.1,vi_vn
564,b9dac638-cc17-4d03-a456-ccf173c9464d,3,"Xoay ngang chưa được tốt lắm, dọc thì full màn, cần bổ sung thêm chỉ báo vào biểu đồ để có thể thuận tiện phân tích. Đa phần ở mức cơ bản",2024-04-03 00:17:36,5.5.2,5.5.2,vi_vn
1323,ed66daf9-cc37-4ec8-a2f0-a95c6580beb1,1,"App cực ngu, tìm kiếm, sao kê tài khoản, thực hiện margin tìm tất cả danh mục không thấy , sắp xếp rối tít mù . Mặc dù cũng dân công nghệ mà ko dùng nổi cái app này",2022-07-18 19:26:33,3.3.2,3.3.2,vi_vn
3060,d1e182cd-53a7-4a66-b8b1-de6afda48329,2,Please update app tobe able modify/cancel sell/buy command base on stock exchange. It should not lock all command on other stock like HNX UpCom,2021-06-10 15:01:54,3.0,3.0,en_vn
438,166a3e51-08f2-444f-adc9-edf731626ca0,5,Đâu tư tài chính,2024-08-16 07:59:48,5.7,5.7,vi_vn
2509,d59b0ef3-d05e-4e96-b35c-24777d3c893c,5,Ok,2020-10-09 01:53:38,NaN,NaN,vi_vn
871,7b9369ee-4dab-4d04-b86e-18e7893af68a,1,Hỗ trợ người dùng như cc,2023-10-20 11:07:01,5.1.3,5.1.3,vi_vn
2970,00193fc4-085c-4326-86cb-4221f68c58eb,3,"Lots of functionality bunched into one app makes TCBS a one-stop finance shop. However, technical issues are way too often including funds lockup today. Otherwise, 4.5star. Innovative & great potential.",2021-11-23 12:42:31,3.1.1,3.1.1,en_vn
1837,fd8b849e-938f-455e-80ac-8477b882fadb,1,Hôm nay tcbs lại thử thách tính kiên nhẫn của nđt. Ko đăt lênh được là thế nào nhỉ,2021-11-22 11:04:35,3.1.1,3.1.1,vi_vn
1116,e584f7a0-8925-4e26-9d93-3ff5c6a77fc2,1,"1 app lag và load chậm 2 năm nay ko cải thiện 2 giao diện bừa bộn thiếu khoa học 3 đặt lệnh tuy nhanh bố cục giao diện lỗi thời ,nhàm chán , khó sử dụng cho các lệnh khác nhau. 4 nạp và rút tiền còn lâu, nhất là rút khác ngân hàng . 5 HIỂN THỊ SAI GIÁ, SAI TÀI SẢN, SAI LỢI NHUẬN ...",2023-04-08 08:46:35,5.0,5.0,vi_vn
30,af8a59ca-c7f4-42e5-8334-271f9748bc89,5,Cải thiện UX/UI đơn giản nhưng nhiều chức năng sẽ tốt hơn.,2026-07-03 14:38:16,6.4.5,6.4.5,vi_vn
184,cae11e9b-ac4d-45ab-b66c-d68ac491a2d9,1,"Quá tệ, cho tiền vào đầu tư đến lúc rút tiền không cho xác thực tài khoản ngân hàng, liên hệ support thì toàn chát tự động, ko có nhân viên nào hỗ trợ, xác định mất",2025-08-15 16:28:02,6.1.2,6.1.2,vi_vn
2653,980f0ef8-74d0-4a90-b910-b08628916648,4,"App dạo này đặt lệnh hay nhảy linh tinh quá, điền mã CP xong điền giá thì mã CP lúc còn lúc ko, cảm giác rất khó chịu, trên web cũng tình trạng tương tự",2020-03-25 07:35:10,2.6.1,2.6.1,vi_vn
2276,6b93b5c7-9199-48e0-b279-5e6918137359,1,"Rất hay lỗi, ko hủy hay sửa lệnh đc, ko hiện giá trị.",2021-04-13 11:02:30,2.9,2.9,vi_vn
3192,696ac4f6-8230-4066-8807-08338e9ea827,1,"Ultra low performance. Switch tabs & menus is much slower than other apps. Even if entering OTP is not related the Internet, the app is slow and keep loading for nothing.",2020-03-16 20:06:22,2.6.1,2.6.1,en_vn

Earliest 20

,reviewId,score,content,at,reviewCreatedVersion,appVersion,collection_locale
3222,d9cf435b-e857-4894-9aaf-363abf995b71,5,Very convenience to trade on Vietnam stock market,2015-08-13 11:10:30,1.0,1.0,en_vn
3221,971758e7-1b59-445f-941f-e44c69810165,5,Clean and Fast. Menu needs to improve for more convenient.,2015-08-24 15:06:49,NaN,NaN,en_vn
2711,0f1413df-783e-42a6-8532-e1654d507521,5,Ok,2015-09-02 11:07:10,1.0,1.0,vi_vn
3220,e8718449-090f-4cbd-8471-9b767f2065fc,1,Phần mềm không cài đc trên note 4 :(,2015-09-13 19:32:39,NaN,NaN,en_vn
2710,d916d16d-74cd-41ca-86ca-fb57447b18da,4,Phần mềm cập nhật thông tin chậm. Đăng nhập đôi lúc k vào được. Tài khoản tổng tính hay bị sai khi giá cổ phiếu tăng lên hay giảm xuống. Phần trăm lãi bị nhầm lẫn khi chuyển cổ phiếu qua lại giữa thường và ký quỹ. Nhìn chung ứng dụng này chưa tốt cả về sự mượt mà lẫn cập nhật thông tin thị trường.,2016-08-14 08:24:52,1.1,1.1,vi_vn
2709,18ab7cb9-5b97-4365-a57e-882af1ce245a,4,"Thông tin cập nhật hay bị sai, giá cp lên xuống ko được cập nhật đúng. Không cho bán lô lẻ như FPTS. Hy vọng TCBs sớm fix lỗi.",2016-09-19 11:33:26,1.1,1.1,vi_vn
3219,0de9b206-e6bf-4af4-9c22-b5c7384f77b3,1,Vừa đăng nhập xong 2' thì tự quit,2016-10-25 14:46:57,1.1.1,1.1.1,en_vn
2708,9bbd9691-fab8-4b68-9aad-24f1f40c0742,2,Cập nhật chậm. Tính sai tổng tài sản. Đề nghị cập nhật,2017-07-12 13:02:47,1.1.2,1.1.2,vi_vn
2707,f98616ef-454c-4196-a4fb-65d9ffc1ae97,2,"1. Bảng giá hiển thị bị làm tròn số. Vd: giá 39.15 làm tròn thành 39.2 2. Danh mục đầu tư chưa tính lãi/lỗ tổng cộng 3. Không có thông tin về cổ phiếu ( biểu đồ giá + klg, báo cáo tài chính: tổng quan + chỉ tiêu + chỉ số, tin tức thị trường liên quan,...) 4....",2017-10-09 11:09:47,1.1.6,1.1.6,vi_vn
3218,27976d92-a850-4c7f-bc10-aa36403ade07,1,"Cài đặt xong nhưng không thể đăng nhập sử dụng, liên tục báo lỗi connection failed, mặc dù đăng nhập bằng account & code đang sử dụng trên bản web.",2017-12-02 10:39:36,1.1.6,1.1.6,en_vn
2706,1d5a95f5-3633-4553-b1de-dd37e47a0a0e,1,Ứng dụng quá kém,2018-01-18 19:45:53,1.1.6,1.1.6,vi_vn
3217,6e6e2256-a5b9-47e5-9904-1c16de158086,1,Đăng nhâp liên tục báo Đang đăng nhập ở nơi khác. Phải nhập rất nhiều lần mới vào đc. Dữ liệu chi tiết giá hiển thị liên tục bị mất. Cái app k thể tệ hơn. Quá thất vọng,2018-03-30 11:20:25,1.1.6,1.1.6,en_vn
2705,cea24230-a9da-4378-9975-5f5b7861f81f,2,Lỗi trên android,2018-05-09 13:25:53,NaN,NaN,vi_vn
2704,28826774-b7fb-426e-924c-e89362e11099,3,Khi nhập mã CK phân biệt chữ hoa chữ thường - ko tiện,2018-05-10 10:04:26,1.1.6,1.1.6,vi_vn
3216,3fb54262-50d3-40da-8c76-ce93774a02e0,1,Ứng dụng bị lỗi hoàn toàn mong ad fix sớm,2018-05-18 08:37:35,1.1.6,1.1.6,en_vn
2703,2f36cd1c-0aed-416c-97a0-0e6050b14dab,4,Tạm ổn,2018-07-05 23:43:57,1.1.6,1.1.6,vi_vn
2702,82b65da1-0d60-4fc5-8c36-02ea47bbfc72,1,Không đăng nhập được.,2018-07-11 04:59:53,NaN,NaN,vi_vn
2701,ba501936-f6b7-4acf-a53b-019b2f5a3939,1,Ứng dụng chất lượng quá kém,2018-07-20 14:19:33,1.1.6,1.1.6,vi_vn
2700,cfb8b137-90bf-4efd-900e-c2d59f954bcc,3,Ứng dụng hay bị lag ra. Hi vọng TCB fix sớm,2018-08-03 07:24:10,1.1.7,1.1.7,vi_vn
2699,10af4e10-4652-4c23-9faf-139e64150383,1,Quá tệ. Thiết lập chán chê rồi vẫn chưa có thông tin tài khoản đăng nhập.,2018-08-20 09:07:36,1.1.7,1.1.7,vi_vn

Latest 20

,reviewId,score,content,at,reviewCreatedVersion,appVersion,collection_locale
0,6638c299-2864-4386-837e-41064b75be48,1,sao cứ cứng đơ không nhích nhút gõ bất kỳ một chữ nào được....,2026-09-21 12:13:27,NaN,NaN,vi_vn
1,45b7bb0f-cd74-43a9-9b85-bd050b6a1f9f,1,Mới dùng thử . App giao diên quá chán. Dùng tcbs . Mà phải vào ssi xem giá . .ap quá chán luôn .,2026-09-21 05:51:18,6.4.5,6.4.5,vi_vn
2,4ae66065-e785-4516-a20d-51040c7a80d2,1,"rẻ rách, đã rườm rà còn khó xài",2026-09-18 18:49:22,6.4.5,6.4.5,vi_vn
3,f93f9a8e-c094-4ceb-8268-f4ba73dbb18c,1,"bắt làm chữ ký số mà cứ chụp ảnh xong là đơ, ko làm đc cái gì nữa, xóa đi cài lại vẫn thế",2026-09-15 22:04:51,6.4.5,6.4.5,vi_vn
4,ef9573f5-cac7-4b27-857a-f29bebf2c4d2,3,"Tôi đang sở hữu quỹ tcef đặt mua thêm ccq ngay trong tcef mà khi đặt lệnh lại lòi ra lệnh mua tcbf là sao vậy, ai code app kỳ vậy",2026-09-14 08:56:29,6.4.5,6.4.5,vi_vn
5,b60631dc-52f7-4a6e-ab62-777981d617ec,1,"Giao diện app quá tệ. Tính năng cơ bản như xem chart và đặt lệnh chuyển qua lại rất phức tạp, tôi muốn vừa xem chart nhanh vừa đặt lệnh nhiều ngày (24/7) đơn giản, mà app quá rườm rà, giao diện nhiều tính năng rác không dùng đến chiếm hết chỗ. Muốn xem danh mục của tôi đang giữ biến động thế nào...",2026-09-11 15:57:15,6.4.5,6.4.5,vi_vn
6,7d25eb7f-ac40-4de4-8943-5ab02a03cdbf,1,"App Techcombank Mobile nhanh bao nhiêu thì app TCBS chậm bấy nhiêu, đó là vì TCB mobile có giao diện đơn giản. Để cải thiện, các bạn cần đơn giản hóa giao diện, các cửa sổ lựa chọn chỉ nên hiện những gì cần thiết, cơ bản (các tính năng thông minh khác dành cho nhà đầu tư chuyên nghiệp nên được c...",2026-09-09 06:36:39,NaN,NaN,vi_vn
7,84a4e782-1615-4764-ad24-3974c5da8eb0,2,app lag giật khó dùng,2026-09-08 08:36:53,6.4.5,6.4.5,vi_vn
2712,7fd64ff8-fbd4-4520-a656-c439f9e4443d,1,"Đội ngũ hỗ trợ xử lý chậm chạp, lề mề. Tài khoản khách hàng cần mở khóa, phải chạy lên chi nhánh TCB kí giấy. Rùi phải đợi 2-3 ngày vận chuyển giấy tờ từ TCB ra TCBS chi nhánh HN. Sau đó phải đợi xử lý tờ giấy, rùi đợi 24 giờ để mở khóa. Loằng ngoằng như thời cổ đại.",2026-09-05 11:12:28,NaN,NaN,en_vn
8,74c2b3de-07a9-4e83-afe4-76ce8134f8f0,1,"Rất tệ yêu cầu mã iOTP mà chờ gần 30p không có , liên hệ nhân viên thì không được , hệ thống quản lý quá kém",2026-08-29 21:30:32,6.4.5,6.4.5,vi_vn
9,5bac4bc7-ad1e-45fe-858c-84c7185e971a,1,"Ứng dụng lỏi, vô tạo tài khoản bấm tiếp tục mãi k đc",2026-08-28 23:10:48,6.4.14,6.4.14,vi_vn
10,9450f8ac-d9ba-4f47-b7f2-3271066a7707,1,app lỗi vcl. không quay vid xác thực khuôn mặt được. quá tệ,2026-08-25 10:25:19,6.4.5,6.4.5,vi_vn
11,9e1764d8-c3f8-42aa-ae90-cd5c55046620,2,"Phần đặt lệnh, hiển thị các mức giá chờ khớp chưa được dễ dùng như của FPT và SSI",2026-08-24 16:45:37,NaN,NaN,vi_vn
12,036f8109-831e-469c-bbe2-1b284129e69b,5,Tôi thấy dùng tốt bình mà sao mọi người bình luận tệ thế nhỉ hay do mới tham gia thị trường nên vậy,2026-08-21 17:39:02,6.4.5,6.4.5,vi_vn
2713,ef99efd2-9f92-42ab-8b4c-3c4e41370ef3,1,"Very bad exp. It required users to input a certain message in each transfer (your full name and account in TCBS (aka Techcombank Securities, this app). Even if you transfer money from your Techcombank app, but forgot to input that abovementioned info, your money goes to vague. It doesn't return ...",2026-08-18 15:10:00,6.4.5,6.4.5,en_vn
13,b80c2d64-7ce6-4036-9237-860697ee5178,1,"chậm, lag quá ạ",2026-08-12 15:23:48,6.4.5,6.4.5,vi_vn
14,70b1c57f-f62a-4b30-b5cb-08fef6063ccd,2,"App làm rối quá, làm như SSI hay MBS cho dễ sử dụng.",2026-08-10 15:03:03,6.4.5,6.4.5,vi_vn
15,01ad6ded-2aab-45a5-b0c7-e94d5828b921,1,lag,2026-08-07 09:24:22,6.4.1,6.4.1,vi_vn
16,e5ec7f53-687e-43a7-aa2c-55e6ead04049,1,"App quá chán. Lúc cần bán thì k vào dc, dựt lag quá",2026-08-04 20:07:41,6.4.5,6.4.5,vi_vn
17,5d89ab13-4007-48a8-8e02-6279e531d636,5,"tạm thời Ok. +Phần đăng ký: đăng ký online hôm trước thì hôm sau được duyệt để mua rồi. + Phí giao dịch : khi mua là phí 0.03% khá rẻ, khi bán là phí 0.03% và thuế TNCN 0.1% + Sau khi chuyển tiền thì tầm 1 phút mới cập nhật số dư. + Sau khi bán là phần tiền bán 2 ngày sau mới về tài khoản để rút...",2026-08-01 17:01:26,6.4.5,6.4.5,vi_vn

## Very Short Reviews

For consistency with the cleaning audit, character length is calculated on a temporary display-only string after trimming and collapsing whitespace. The rule is `length <= 10`. No raw value is changed or removed. A short review such as "Tệ", "Good", "Ok", or "Tốt" can still be valid.

In [31]:
def qa_text_length(series):
    return series.astype("string").str.replace(r"\s+", " ", regex=True).str.strip().str.len()

app_short_mask = qa_text_length(app_store_df["content"]).le(10)
google_short_mask = qa_text_length(google_play_df["content"]).le(10)
assert int(app_short_mask.sum()) == 57
assert int(google_short_mask.sum()) == 476
print(f"App Store very short reviews: {int(app_short_mask.sum()):,}")
display(app_store_preview[app_short_mask].head(50))
print(f"Google Play very short reviews: {int(google_short_mask.sum()):,}")
display(google_play_preview[google_short_mask].head(50))

App Store very short reviews: 57

,review_id,rating,title,content,updated_at,app_version,storefront,lang
5,14467591535,5,NGUYEN VAN PHUONG,Namkuto,2026-08-24T12:29:06-07:00,6.4.4,vn,unknown
27,14142865973,1,Ai như tôi không nạo tiền vào không lâu tiền bay hết sạch,Chắn,2026-06-04T06:07:36-07:00,6.4.4,vn,unknown
34,14009628721,1,Lỗi hiển thị sai giá ko thể mua bán,App lỗi tệ,2026-04-29T08:34:18-07:00,6.4.3,vn,unknown
47,14007820033,1,app lởm,lởm vl,2026-04-28T19:37:47-07:00,6.4.3,vn,unknown
95,13732893373,1,Nạo tiền không và tài khoản,Bad,2026-02-09T21:05:11-07:00,6.4.1,vn,unknown
160,13276981462,1,App thường xuyên treo lúc cần bán,Tệ,2025-10-17T00:44:07-07:00,6.1,vn,unknown
192,12964759767,1,App gì mà lag lộn lên,1 điểm,2025-08-01T15:41:55-07:00,6.0,vn,unknown
201,12889467768,2,Lỗi,Hay bị lỗi,2025-07-13T23:07:33-07:00,6.0,vn,unknown
230,12729702813,5,Good app,Good app,2025-06-02T20:41:08-07:00,5.9,vn,unknown
231,12727113643,5,105CTOIYEUVN tôi thích bảng giá,Rất hay,2025-06-02T05:18:56-07:00,5.9,vn,unknown
250,12605203687,2,Bảo trì kiểu gì mà 2 ngày chưa rồi vậy,Tệ,2025-04-30T20:08:57-07:00,5.9,vn,unknown
258,12529231767,1,"App lag, giật, xấu dỏm, giam tiền nhà đầu tư",Quá tệ,2025-04-11T00:45:57-07:00,5.9,vn,unknown
277,12400663065,2,Ko rút dk,Ko rút dk,2025-03-09T07:18:02-07:00,5.8.5,vn,unknown
279,12387003343,1,Lỗi đăng nhập - gọi hỗ trợ chỉ có tổng đài tự động,Hỗ trợ kém,2025-03-05T19:00:38-07:00,5.8.5,vn,unknown
280,12383638403,1,Quá lằng nhằng. Giao diện quá nhiều sản phẩm. Dùng rất rối,Chán,2025-03-04T22:23:29-07:00,5.8.5,vn,unknown
287,12301648806,1,"Hay bị lỗi chuyển tiền, nhắn tin không xử lý",Tệ,2025-02-12T03:04:36-07:00,5.8.5,vn,unknown
300,12084617137,5,Không chê điểm gì,6 sao,2024-12-20T04:30:44-07:00,5.8.2,vn,unknown
304,12004038909,1,Lỗi liên tục,1 sao,2024-11-28T22:26:10-07:00,5.8.2,vn,unknown
310,11894826169,1,Khó dùng và hay treo,App dở hơi,2024-10-31T00:32:47-07:00,5.8.2,vn,unknown
318,11809107324,5,OK,Được,2024-10-07T16:07:22-07:00,5.8,vn,unknown
320,11801692398,5,Oke,Oke,2024-10-05T15:50:08-07:00,5.8,vn,unknown
340,11743600482,5,105CD59338 tôi thích bảng giá,hi,2024-09-19T23:40:49-07:00,5.7,vn,unknown
348,11741247423,5,Tks,Tuyệt,2024-09-19T07:38:14-07:00,5.7,vn,unknown
349,11741201798,5,105CXX1988,105CXX1988,2024-09-19T07:24:33-07:00,5.7,vn,unknown
353,11740576811,5,105CNGHI87 tôi thích bảng giá,Đảm bảo,2024-09-19T04:01:10-07:00,5.7,vn,unknown
358,11740234857,5,Stk 105CAA0395,Rất tuyệt,2024-09-19T01:27:28-07:00,5.7,vn,unknown
359,11740203337,5,Ứng dụng rất hay là bổ ích,105CE77498,2024-09-19T01:11:43-07:00,5.7,vn,unknown
364,11740117898,5,Dịch vụ tốt,Hài lòng,2024-09-19T00:28:12-07:00,5.7,vn,unknown
380,11739674478,5,Good,Good,2024-09-18T20:41:33-07:00,5.7,vn,unknown
382,11739650810,5,TCBS,Good,2024-09-18T20:30:05-07:00,5.7,vn,unknown
385,11739540108,5,105CF25895,105CF25895,2024-09-18T19:38:12-07:00,5.7,vn,unknown
386,11739533502,5,105CTOIYEUVN tôi thích bảng giá,105CP31991,2024-09-18T19:35:14-07:00,5.7,vn,unknown
389,11739494710,5,Tuyệt,Tuyệt,2024-09-18T19:18:12-07:00,5.7,vn,unknown
390,11739482732,4,Đánh giá,Ổn áp,2024-09-18T19:13:10-07:00,5.7,vn,unknown
417,11737709558,5,Tuyệt,Phí tốt,2024-09-18T07:45:06-07:00,5.7,vn,unknown
418,11737687886,5,H,105C2610H9,2024-09-18T07:38:18-07:00,5.7,vn,unknown
423,11737591937,5,Good,Nice,2024-09-18T07:08:46-07:00,5.7,vn,unknown
426,11737569918,5,Đánh giá,Hài lòng,2024-09-18T07:02:03-07:00,5.7,vn,unknown
430,11737533387,5,30 ixu,105CI90286,2024-09-18T06:50:55-07:00,5.7,vn,unknown
434,11737328061,5,Tuyệt vời,105CA18669,2024-09-18T05:47:47-07:00,5.7,vn,unknown
437,11737301876,5,105CA37858,Ok,2024-09-18T05:39:35-07:00,5.7,vn,unknown
442,11737242792,5,Rất tốt,Rất hay,2024-09-18T05:20:59-07:00,5.7,vn,unknown
445,11737227049,5,Tôi yêu TCBS,105C8386D8,2024-09-18T05:15:56-07:00,5.7,vn,unknown
446,11737209733,5,Ht,T,2024-09-18T05:10:15-07:00,5.7,vn,unknown
447,11737205326,5,Đánh giá,Tốt,2024-09-18T05:08:45-07:00,5.7,vn,unknown
452,11737168948,5,Tốt,Tốt,2024-09-18T04:56:25-07:00,5.7,vn,unknown
456,11737104569,5,Ứng dụng rất tốt,5 sao,2024-09-18T04:33:43-07:00,5.7,vn,unknown
457,11737096946,5,5 sao,105CA84418,2024-09-18T04:30:57-07:00,5.7,vn,unknown
470,11737005757,5,105CD99529,Ok,2024-09-18T03:56:38-07:00,5.7,vn,unknown
476,11736971959,5,Ứng dụng tốt,105CH68998,2024-09-18T03:42:57-07:00,5.7,vn,unknown

Google Play very short reviews: 476

,reviewId,score,content,at,reviewCreatedVersion,appVersion,collection_locale
15,01ad6ded-2aab-45a5-b0c7-e94d5828b921,1,lag,2026-08-07 09:24:22,6.4.1,6.4.1,vi_vn
20,07616126-4fd6-4860-a991-a0a6ea51f192,5,mong đợi,2026-07-24 10:33:14,6.4.5,6.4.5,vi_vn
21,56f40fd1-9968-4020-a53d-7faa5f81b4ba,5,good,2026-07-16 08:30:18,5.8.13,5.8.13,vi_vn
49,028fcd26-9ed7-4edb-a256-5d54363dfa43,1,DV CSKH tệ,2026-05-15 13:12:47,6.4.3,6.4.3,vi_vn
64,8832565b-75c1-45d2-8fc2-a846e4f983be,5,dễ dùng đó,2026-04-17 11:21:53,6.4.1,6.4.1,vi_vn
76,12a15533-34a5-4b70-8535-3bee8c3a3f30,5,ok,2026-04-15 15:39:08,6.4.1,6.4.1,vi_vn
95,eddf39d9-bd84-4593-8b55-0d8756ca835e,1,ap lỏ vl,2026-03-01 19:01:57,6.4.1,6.4.1,vi_vn
99,729f405c-971f-47b7-803d-ed285f1e2299,5,ok,2026-02-22 01:15:19,6.4.1,6.4.1,vi_vn
166,e17a1244-02e2-46a7-b4e8-ef5e21919c2c,1,ko vào dc,2025-09-15 10:29:27,6.2,6.2,vi_vn
174,a604cb52-b613-43b7-98e2-58a855dd280c,5,rất ok,2025-09-05 16:08:32,6.2,6.2,vi_vn
195,b8566b33-1451-4fbc-8976-a687b982c667,1,Toàn lỗi,2025-07-22 08:59:59,6.1,6.1,vi_vn
208,e26e9a86-cd65-4d0a-89c0-1b8c74dea203,5,ok,2025-07-05 06:04:27,5.9,5.9,vi_vn
213,e581e069-2b70-4946-b0d8-c5f81860acb0,5,tốt,2025-06-25 23:30:50,5.9,5.9,vi_vn
214,ee25f9c0-a463-4ec0-aaf4-e7e420f53c2d,5,ok tốt,2025-06-24 19:15:50,5.9,5.9,vi_vn
217,f55b417f-6811-4336-8eb4-15f53f36fc52,5,ok,2025-06-12 21:25:19,5.9,5.9,vi_vn
227,a3bcab51-d400-4509-aa9e-e82dc0a3dc57,5,ok,2025-05-28 06:09:20,5.9,5.9,vi_vn
258,ca0eb48c-8b0d-4c50-9638-b4ec1a4b3450,1,nice,2025-03-13 16:05:11,NaN,NaN,vi_vn
263,01c61fdf-61e9-4a21-9167-382c2205e006,2,App quá tệ,2025-03-10 09:13:03,NaN,NaN,vi_vn
282,b688ac8c-082a-4976-8c70-99f9430abc75,1,Tệ,2025-02-02 18:47:35,5.1.3,5.1.3,vi_vn
283,29fe0daf-fc2a-41bc-b751-a5e3b93289ce,5,Ok,2025-01-26 11:18:18,5.8.12,5.8.12,vi_vn
295,7e64ea2c-b419-4846-adbc-7fb6e7f32d37,5,Tốt,2025-01-13 00:58:47,5.8.11,5.8.11,vi_vn
297,0e006d81-5f56-4aa0-a8c0-74344ace1672,5,Tốt,2025-01-03 15:14:52,5.8.11,5.8.11,vi_vn
309,446d8547-093a-4cc5-ae1d-66fb292eb06b,5,Good,2024-12-05 11:56:28,5.8.3,5.8.3,vi_vn
315,c3bb50f4-57ac-4536-8287-4101d6754c58,5,Ok hay đấy,2024-11-17 11:05:34,5.8.3,5.8.3,vi_vn
325,cbbc87cf-77ee-4fec-931e-ea3e9a56ba2a,1,Tệ,2024-10-21 11:32:59,5.8.3,5.8.3,vi_vn
326,4e83db00-f249-4eed-aa42-7c066be696aa,5,Ok,2024-10-20 08:07:11,NaN,NaN,vi_vn
338,2b3ebee6-b34e-4e99-9fd6-46bbf8ea3e47,5,Dễ sử dụng,2024-09-25 21:25:34,NaN,NaN,vi_vn
365,d2c4f9dd-9d64-4571-8e29-4a39f1330a39,5,Tôi yêu vn,2024-09-19 00:54:35,5.7.2,5.7.2,vi_vn
366,4cd4f4ae-def1-404e-9d8c-3f7f7a70ac83,5,Tốt,2024-09-18 23:55:28,5.5.3,5.5.3,vi_vn
371,17f40f7e-398f-40c3-bb06-a0596663fb45,5,Rất ok,2024-09-18 20:29:55,5.7.2,5.7.2,vi_vn
373,a8a08c76-d812-4090-9c9b-c2ccad04463c,5,good:)),2024-09-18 20:15:44,5.7.2,5.7.2,vi_vn
379,9076f127-1265-4ff7-b5f0-b9ac076d8eec,5,Tốt,2024-09-18 18:53:26,NaN,NaN,vi_vn
381,af2107f8-943c-4dab-9a0e-133f4cad0d08,5,Tốt quá,2024-09-18 18:51:10,5.7.2,5.7.2,vi_vn
384,9bdae312-cbfe-49bc-8023-43bf37d5f09a,5,Good spp,2024-09-18 18:35:11,NaN,NaN,vi_vn
393,7cd896f5-3cb8-48d6-920c-a6a885b5cbd1,5,Good,2024-09-18 17:03:06,NaN,NaN,vi_vn
400,10a684a4-b631-4d71-a73e-ec81fbca10f0,5,App tốt,2024-09-18 16:26:52,NaN,NaN,vi_vn
410,365ba7d3-1d12-4f97-a2e5-3652be783b48,5,Good,2024-09-18 15:54:11,5.7.2,5.7.2,vi_vn
412,cb652132-8302-42aa-9831-282e11457abb,5,Rất tốt,2024-09-18 15:16:03,5.7.2,5.7.2,vi_vn
416,b4c1f818-addb-4dd3-887b-8b895cdd1b69,4,Ok,2024-09-10 23:01:17,5.7.2,5.7.2,vi_vn
421,dc997070-5cab-4ede-aa9e-5b362806da23,5,tôt,2024-08-25 05:09:53,NaN,NaN,vi_vn
433,0f7d2515-1960-4cde-a19e-380bf623a839,5,Ok,2024-08-17 12:40:13,NaN,NaN,vi_vn
450,397577ab-f5d5-45f1-8384-459f9c63829b,5,Rất thích,2024-08-15 07:17:47,5.7,5.7,vi_vn
453,1bcc45c3-97c6-4f35-ad70-82376abb96ff,5,Ok,2024-08-15 05:03:06,NaN,NaN,vi_vn
456,5f4d8659-cbc2-4de6-beae-658bdee51151,5,105CDDATDD,2024-08-14 23:14:13,5.7,5.7,vi_vn
462,472325d4-902a-4b59-b14b-c9caf5704525,5,Tốt,2024-08-14 18:02:18,NaN,NaN,vi_vn
465,c616fb4d-feaa-4362-96f0-e85383b75b5a,5,Tuyệt vời,2024-08-14 14:34:21,5.6.4,5.6.4,vi_vn
471,f1d826aa-5886-4f68-9d1e-dc5c4fdf35e9,5,Tốt,2024-08-14 13:05:41,5.6.2,5.6.2,vi_vn
476,d8add84a-e578-4b8e-8e44-b5c134a3e6a0,5,Ổn,2024-08-14 12:42:00,5.6.5,5.6.5,vi_vn
477,6276e5fd-b215-4ce5-89ac-7769de723c7e,5,Rất tốt,2024-08-14 12:28:41,5.7,5.7,vi_vn
478,0f36b046-ab38-438e-9224-247ee7edd7b3,5,TỐT,2024-08-14 12:25:49,5.7,5.7,vi_vn

## Exact Duplicate Text Inspection

Exact duplicate text is flagged across the current combined raw inputs. Distinct review IDs are retained: identical wording does not prove that reviews or users are duplicates.

In [32]:
text_index = pd.concat([
    app_store_df[["review_id", "content"]].rename(columns={"content": "review_text_raw"}).assign(source="App Store"),
    google_play_df[["reviewId", "content"]].rename(columns={"reviewId": "review_id", "content": "review_text_raw"}).assign(source="Google Play"),
], ignore_index=True)
exact_text_counts = text_index["review_text_raw"].value_counts(dropna=False)
duplicate_groups = exact_text_counts[exact_text_counts > 1]
duplicate_records_mask = text_index["review_text_raw"].isin(duplicate_groups.index)
duplicate_records = text_index[duplicate_records_mask].copy()
assert len(duplicate_groups) == 69
assert len(duplicate_records) == 417
print(f"Exact duplicate-text groups: {len(duplicate_groups):,}")
print(f"Records involved: {len(duplicate_records):,}")
display(duplicate_groups.rename("count").head(50).to_frame())

DUPLICATE_TEXT_TO_INSPECT = ""  # Paste an exact text value to inspect underlying IDs.
if DUPLICATE_TEXT_TO_INSPECT:
    display(duplicate_records[duplicate_records["review_text_raw"].eq(DUPLICATE_TEXT_TO_INSPECT)])

Exact duplicate-text groups: 69
Records involved: 417

                                                count
review_text_raw
Ok                                                 69
Tốt                                                41
Good                                               39
Quá tệ                                             27
Tệ                                                 19
105CTOIYEUVN                                       14
ok                                                 14
Rất tốt                                            12
Tuyệt vời                                          11
"105CTOIYEUVN tôi thích bảng giá"                   7
Tuyệt                                               6
tốt                                                 5
App quá tệ                                          5
Very good                                           5
Tot                                                 5
Hài lòng                                            4
Ứng dụng tốt                                        4
Dễ sử dụng                                          4
Vô trang 𝐕𝐚𝐲𝟗.𝐂𝟎𝐌 để vay 0% + kiếm 900k             4
App hay lỗi                                         4
Quá kém                                             4
Lỗi liên tục                                        4
Tồi tệ                                              4
Tệ hại                                              4
Hay bị lỗi                                          3
Good app                                            3
Chán                                                3
Oke                                                 3
Nice                                                3
Good app, vào VAY9 . C0M để nhận 9tr vậy thôi       3
"105CTOIYEUVN tôi thích bảng giá                    3
105CTOIYEUVN tôi thích bảng giá.                    3
Quá chán                                            3
quá tệ                                              3
Vô trang 𝑽𝒂𝒚𝑻𝒐𝒕𝑵𝒉𝒂𝒕 vay 0% nhận 590k free ngay      3
Quá tệ.                                             3
App nhiều lỗi                                       2
App rất lag                                         2
Rất hay                                             2
Ứng dụng ok                                         2
Tôi thích bảng giá                                  2
5 sao                                               2
good                                                2
Rất tiện lợi                                        2
"105CTOIYEUVN tôi thích bản giá"                    2
Rất ok                                              2
105CTOIYEUVN tôi thích bảng đánh giá                2
105CTOIYEUVN tôi thích bảng giá"                    2
105CTOIYEUVN tôi thích bảng giá".                   2
tuyệt vời                                           2

## Find Review by ID

In [33]:
APP_STORE_REVIEW_ID = ""
GOOGLE_PLAY_REVIEW_ID = ""

if APP_STORE_REVIEW_ID:
    display(app_store_df[app_store_df["review_id"].astype(str).eq(str(APP_STORE_REVIEW_ID))])
else:
    print("Set APP_STORE_REVIEW_ID to inspect an App Store review.")

if GOOGLE_PLAY_REVIEW_ID:
    display(google_play_df[google_play_df["reviewId"].astype(str).eq(str(GOOGLE_PLAY_REVIEW_ID))])
else:
    print("Set GOOGLE_PLAY_REVIEW_ID to inspect a Google Play review.")

Set APP_STORE_REVIEW_ID to inspect an App Store review.
Set GOOGLE_PLAY_REVIEW_ID to inspect a Google Play review.

## Date Distribution Quick View

These simple count tables provide QA context only. They do not select an analysis time range.

In [34]:
app_display_dates = pd.to_datetime(app_store_df["updated_at"], utc=True, errors="coerce")
google_display_dates = pd.to_datetime(google_play_df["at"], utc=True, errors="coerce")
app_year_counts = app_display_dates.dt.year.value_counts().sort_index().rename("App Store")
google_year_counts = google_display_dates.dt.year.value_counts().sort_index().rename("Google Play")
display(pd.concat([app_year_counts, google_year_counts], axis=1).fillna(0).astype(int))

app_month_counts = app_display_dates.dt.strftime("%Y-%m").value_counts().sort_index().rename("App Store")
google_month_counts = google_display_dates.dt.strftime("%Y-%m").value_counts().sort_index().rename("Google Play")
print("Latest 36 observed months")
display(pd.concat([app_month_counts, google_month_counts], axis=1).fillna(0).astype(int).tail(36))

      App Store  Google Play
2023          4          527
2024        221          477
2025        166          209
2026        131          148
2015          0            4
2016          0            3
2017          0            3
2018          0           14
2019          0           45
2020          0          260
2021          0         1188
2022          0          345

Latest 36 observed months

         App Store  Google Play
2021-04          0           27
2021-05          0           52
2021-06          0           73
2021-07          0           39
2021-08          0           42
2021-09          0           24
2021-10          0           26
2021-11          0          550
2021-12          0          118
2022-01          0           34
2022-02          0           37
2022-03          0           39
2022-04          0           25
2022-05          0           15
2022-06          0           15
2022-07          0           35
2022-08          0           15
2022-09          0           29
2022-10          0           38
2022-11          0           36
2022-12          0           27
2023-01          0           14
2023-02          0           28
2023-03          0           28
2023-05          0           20
2023-06          0           30
2023-10          0           67
2023-11          0           25
2023-12          0          127
2024-01          0           12
2024-02          0            8
2024-03          0          155
2024-05          0           22
2024-06          0           12
2024-07          0           23
2024-08          0           97

## Current Processed Outputs

This section references pipeline status only. Raw inspection above continues to use the two primary raw datasets. No processed file is modified.

In [35]:
clean_df = pd.read_csv(CLEAN_PATH, dtype={"review_id": "string"})
rejected_df = pd.read_csv(REJECTED_PATH, dtype={"review_id": "string"})
assert len(clean_df) == 3745
assert len(rejected_df) == 0
processed_status = pd.Series({
    "clean_dataset": str(CLEAN_PATH.relative_to(PROJECT_ROOT)),
    "clean_rows": len(clean_df),
    "rejected_dataset": str(REJECTED_PATH.relative_to(PROJECT_ROOT)),
    "rejected_rows": len(rejected_df),
})
display(processed_status.rename("value").to_frame())

                                                     value
clean_dataset     01_data/processed/reviews_clean_full.csv
clean_rows                                            3745
rejected_dataset    01_data/processed/reviews_rejected.csv
rejected_rows                                            0

## Manual QA Notes

- **App Store primary v2:** 522 unique reviews, dated 2023-04-14 through 2026-09-14. It is the broadest validated union of the currently saved public-response evidence. This does **not** mean all lifetime App Store reviews, and public endpoint coverage may be unstable.
- **Google Play:** 3,223 unique reviews, dated 2015-08-13 through 2026-09-21, retrieved through the selected Vietnam collection configurations.
- `collection_locale` is collection metadata, not actual review language. The App Store `lang` field is likewise not assumed to be reliable ground truth.
- Public app reviewers are self-selected and are not representative of all TCInvest customers.
- Very short reviews and exact duplicate text with distinct IDs remain valid records unless independent evidence proves otherwise.
- The current clean full-history output has 3,745 rows and zero rejected rows.
- This notebook performs no cleaning, write-back, sentiment analysis, topic modeling, classification, or time-range selection.